@formula @formula-matrix @formula-matrix-combos
Feature: Formula matrix: Combos
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Combos cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name             | expression                                                                                                                                                    |
      | upper_1          | upper(substring(prop("Name"), 0, 3))                                                                                                                          |
      | lower_2          | lower(replaceAll(prop("Name"), " ", "_"))                                                                                                                     |
      | length_3         | length(trim("  " + prop("Name") + "  "))                                                                                                                      |
      | round_4          | round(sum(prop("Num"), prop("Neg")) * 2)                                                                                                                      |
      | round_5          | round(prop("Num") / 3, 2)                                                                                                                                     |
      | format_6         | format(round(prop("Num") / 3, 2)) + "%"                                                                                                                       |
      | formatNumber_7   | formatNumber(prop("Num") * 1000, "commas")                                                                                                                    |
      | formatNumber_8   | formatNumber(prop("Num") / 100, "percent")                                                                                                                    |
      | formatNumber_9   | formatNumber(prop("Neg"), "USD")                                                                                                                              |
      | if_10            | if(contains(lower(prop("Name")), "ada"), format(prop("Num") + 1), "no")                                                                                       |
      | ifs_11           | ifs(empty(prop("Num")), "none", prop("Num") > 5, "high", "low")                                                                                               |
      | join_12          | join(map(prop("Tags"), upper(current)), "-")                                                                                                                  |
      | prop_13          | prop("Tags").map(current + format(prop("Num"))).join(",")                                                                                                     |
      | let_14           | let(total, prop("Num") + prop("Neg"), total > 5 ? "over" : "under")                                                                                           |
      | lets_15          | lets(n, prop("Num"), half, n / 2, format(half) + "/" + format(n))                                                                                             |
      | dateBetween_16   | dateBetween(dateAdd(prop("When"), 1, "days"), prop("When"), "hours")                                                                                          |
      | formatDate_17    | formatDate(dateAdd(parseDate("2024-01-31"), 1, "months"), "YYYY-MM-DD")                                                                                       |
      | formatDate_18    | formatDate(dateSubtract(prop("When"), 1, "weeks"), "YYYY-MM-DD")                                                                                              |
      | formatDate_19    | formatDate(dateStart(dateRange(prop("When"), dateAdd(prop("When"), 3, "days"))), "YYYY-MM-DD")                                                                |
      | formatDate_20    | formatDate(dateEnd(dateRange(prop("When"), dateAdd(prop("When"), 3, "days"))), "YYYY-MM-DD")                                                                  |
      | dateBetween_21   | dateBetween(dateEnd(dateRange(prop("When"), dateAdd(prop("When"), 3, "days"))), dateStart(dateRange(prop("When"), dateAdd(prop("When"), 3, "days"))), "days") |
      | year_22          | year(prop("When")) * 100 + month(prop("When"))                                                                                                                |
      | format_23        | format(year(prop("When"))) + "-" + format(month(prop("When"))) + "-" + format(date(prop("When")))                                                             |
      | hour_24          | hour(dateAdd(prop("When"), 90, "minutes"))                                                                                                                    |
      | minute_25        | minute(dateAdd(prop("When"), 90, "minutes"))                                                                                                                  |
      | fromTimestamp_26 | fromTimestamp(timestamp(prop("When")) + 86400000) == dateAdd(prop("When"), 1, "days")                                                                         |
      | formatDate_27    | formatDate(fromTimestamp(timestamp(prop("When"))), "YYYY-MM-DD")                                                                                              |
      | formatDate_28    | formatDate(parseDate("2024-02-29"), "MMMM D, YYYY")                                                                                                           |
      | formatDate_29    | formatDate(dateAdd(parseDate("2024-02-29"), 1, "years"), "YYYY-MM-DD")                                                                                        |
      | dateBetween_30   | dateBetween(parseDate("2024-12-25"), parseDate("2024-01-01"), "weeks")                                                                                        |
    Then the formula properties show these values for row 1
      | name             | value             |
      | upper_1          | ADA               |
      | lower_2          | ada_lovelace      |
      | length_3         | 12                |
      | round_4          | 11                |
      | round_5          | 2.67              |
      | format_6         | 2.67%             |
      | formatNumber_7   | 8,000             |
      | formatNumber_8   | 8%                |
      | formatNumber_9   | -$2.50            |
      | if_10            | 9                 |
      | ifs_11           | high              |
      | join_12          | A-B-C             |
      | prop_13          | a8,b8,c8          |
      | let_14           | over              |
      | lets_15          | 4/8               |
      | dateBetween_16   | 24                |
      | formatDate_17    | 2024-02-29        |
      | formatDate_18    | 2024-02-27        |
      | formatDate_19    | 2024-03-05        |
      | formatDate_20    | 2024-03-08        |
      | dateBetween_21   | 3                 |
      | year_22          | 202403            |
      | format_23        | 2024-3-5          |
      | hour_24          | 1                 |
      | minute_25        | 30                |
      | fromTimestamp_26 | Yes               |
      | formatDate_27    | 2024-03-05        |
      | formatDate_28    | February 29, 2024 |
      | formatDate_29    | 2025-02-28        |
      | dateBetween_30   | 51                |
    Then the formula properties show these values for row 2
      | name             | value             |
      | upper_1          | NOT               |
      | lower_2          | notion            |
      | length_3         | 6                 |
      | round_4          | 11                |
      | round_5          | 1.25              |
      | format_6         | 1.25%             |
      | formatNumber_7   | 3,750             |
      | formatNumber_8   | 3.75%             |
      | formatNumber_9   | $1.50             |
      | if_10            | no                |
      | ifs_11           | low               |
      | join_12          | B                 |
      | prop_13          | b3.75             |
      | let_14           | over              |
      | lets_15          | 1.875/3.75        |
      | dateBetween_16   | 24                |
      | formatDate_17    | 2024-02-29        |
      | formatDate_18    | 2024-12-24        |
      | formatDate_19    | 2024-12-31        |
      | formatDate_20    | 2025-01-03        |
      | dateBetween_21   | 3                 |
      | year_22          | 202412            |
      | format_23        | 2024-12-31        |
      | hour_24          | 1                 |
      | minute_25        | 30                |
      | fromTimestamp_26 | Yes               |
      | formatDate_27    | 2024-12-31        |
      | formatDate_28    | February 29, 2024 |
      | formatDate_29    | 2025-02-28        |
      | dateBetween_30   | 51                |
    Then the formula properties show these values for row 3
      | name             | value             |
      | upper_1          | ROW               |
      | lower_2          | row3              |
      | length_3         | 4                 |
      | round_4          | 0                 |
      | round_5          | 0                 |
      | format_6         | 0%                |
      | formatNumber_7   | 0                 |
      | formatNumber_8   | 0%                |
      | formatNumber_9   |                   |
      | if_10            | no                |
      | ifs_11           | none              |
      | join_12          |                   |
      | prop_13          |                   |
      | let_14           | under             |
      | lets_15          | 0/                |
      | dateBetween_16   |                   |
      | formatDate_17    | 2024-02-29        |
      | formatDate_18    |                   |
      | formatDate_19    |                   |
      | formatDate_20    |                   |
      | dateBetween_21   |                   |
      | year_22          | 0                 |
      | format_23        | --                |
      | hour_24          |                   |
      | minute_25        |                   |
      | fromTimestamp_26 | No                |
      | formatDate_27    |                   |
      | formatDate_28    | February 29, 2024 |
      | formatDate_29    | 2025-02-28        |
      | dateBetween_30   | 51                |

  Scenario: Combos cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name           | expression                                                              |
      | dateBetween_31 | dateBetween(parseDate("2024-01-01"), parseDate("2024-12-25"), "months") |
      | length_32      | length(split(prop("Note"), " "))                                        |
      | replace_33     | replace(prop("Note"), "World", "AppFlowy")                              |
      | replaceAll_34  | replaceAll(prop("Note"), "l", "L")                                      |
      | match_35       | match(prop("Note"), "[a-z]+").join("\|")                                |
      | match_36       | match(prop("Note"), "[a-z]+").length()                                  |
      | repeat_37      | repeat("ab", prop("Num") / 4)                                           |
      | substring_38   | substring(prop("Name"), length(prop("Name")) - 4)                       |
      | toNumber_39    | toNumber(format(prop("Num"))) + 1                                       |
      | format_40      | format(prop("Num")) + format(prop("Flag"))                              |
      | format_41      | format(prop("Tags")) + "\|" + format(prop("When"))                      |
      | format_42      | format(1 / 3)                                                           |
      | format_43      | format(2 / 3 * 3)                                                       |
      | format_44      | format(0.1 + 0.2)                                                       |
      | format_45      | format(1e21)                                                            |
      | format_46      | format(123456789012345680)                                              |
      | format_47      | format(-0)                                                              |
      | format_48      | format(sqrt(-1))                                                        |
      | format_49      | format(1 / 0)                                                           |
      | sqrt_50        | sqrt(prop("Num") * 2)                                                   |
      | abs_51         | abs(prop("Neg")) + abs(prop("Num"))                                     |
      | round_52       | round(2.5)                                                              |
      | round_53       | round(-2.5)                                                             |
      | round_54       | round(3.14159, 3)                                                       |
      | round_55       | round(1234.5678, -2)                                                    |
      | mod_56         | mod(prop("Num"), 3)                                                     |
      | mod_57         | mod(-7, 3)                                                              |
      | multiply_58    | multiply(add(1, 2), subtract(5, 3))                                     |
      | pi_59          | pi() * 2                                                                |
      | round_60       | round(pi(), 4)                                                          |
    Then the formula properties show these values for row 1
      | name           | value                |
      | dateBetween_31 | -11                  |
      | length_32      | 2                    |
      | replace_33     | Hello, AppFlowy!     |
      | replaceAll_34  | HeLLo, WorLd!        |
      | match_35       | ello\|orld           |
      | match_36       | 2                    |
      | repeat_37      | abab                 |
      | substring_38   | lace                 |
      | toNumber_39    | 9                    |
      | format_40      | 8true                |
      | format_41      | a, b, c\|Mar 5, 2024 |
      | format_42      | 0.333333333333333    |
      | format_43      | 2                    |
      | format_44      | 0.3                  |
      | format_45      | 1e+21                |
      | format_46      | 123456789012345680   |
      | format_47      | 0                    |
      | format_48      |                      |
      | format_49      |                      |
      | sqrt_50        | 4                    |
      | abs_51         | 10.5                 |
      | round_52       | 3                    |
      | round_53       | -2                   |
      | round_54       | 3.142                |
      | round_55       | 1235                 |
      | mod_56         | 2                    |
      | mod_57         | -1                   |
      | multiply_58    | 6                    |
      | pi_59          | 6.28318530717959     |
      | round_60       | 3.1416               |
    Then the formula properties show these values for row 2
      | name           | value              |
      | dateBetween_31 | -11                |
      | length_32      | 1                  |
      | replace_33     | x                  |
      | replaceAll_34  | x                  |
      | match_35       | x                  |
      | match_36       | 1                  |
      | repeat_37      |                    |
      | substring_38   | tion               |
      | toNumber_39    | 4.75               |
      | format_40      | 3.75false          |
      | format_41      | b\|Dec 31, 2024    |
      | format_42      | 0.333333333333333  |
      | format_43      | 2                  |
      | format_44      | 0.3                |
      | format_45      | 1e+21              |
      | format_46      | 123456789012345680 |
      | format_47      | 0                  |
      | format_48      |                    |
      | format_49      |                    |
      | sqrt_50        | 2.73861278752583   |
      | abs_51         | 5.25               |
      | round_52       | 3                  |
      | round_53       | -2                 |
      | round_54       | 3.142              |
      | round_55       | 1235               |
      | mod_56         | 0.75               |
      | mod_57         | -1                 |
      | multiply_58    | 6                  |
      | pi_59          | 6.28318530717959   |
      | round_60       | 3.1416             |
    Then the formula properties show these values for row 3
      | name           | value              |
      | dateBetween_31 | -11                |
      | length_32      | 0                  |
      | replace_33     |                    |
      | replaceAll_34  |                    |
      | match_35       |                    |
      | match_36       | 0                  |
      | repeat_37      |                    |
      | substring_38   | Row3               |
      | toNumber_39    | 1                  |
      | format_40      | false              |
      | format_41      | \|                 |
      | format_42      | 0.333333333333333  |
      | format_43      | 2                  |
      | format_44      | 0.3                |
      | format_45      | 1e+21              |
      | format_46      | 123456789012345680 |
      | format_47      | 0                  |
      | format_48      |                    |
      | format_49      |                    |
      | sqrt_50        | 0                  |
      | abs_51         |                    |
      | round_52       | 3                  |
      | round_53       | -2                 |
      | round_54       | 3.142              |
      | round_55       | 1235               |
      | mod_56         | 0                  |
      | mod_57         | -1                 |
      | multiply_58    | 6                  |
      | pi_59          | 6.28318530717959   |
      | round_60       | 3.1416             |

  Scenario: Combos cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name          | expression                                                                                 |
      | round_61      | round(e(), 4)                                                                              |
      | max_62        | max(prop("Num"), prop("Neg"), 3)                                                           |
      | min_63        | min([prop("Num"), prop("Neg")])                                                            |
      | sum_64        | sum([1, 2, 3], 4)                                                                          |
      | prop_65       | prop("Flag") ? prop("Num") : prop("Neg")                                                   |
      | if_66         | if(prop("Flag"), prop("Tags"), [])                                                         |
      | if_67         | if(prop("Flag"), prop("When"), dateAdd(prop("When"), 1, "days"))                           |
      | formatDate_68 | formatDate(if(prop("Flag"), prop("When"), dateAdd(prop("When"), 1, "days")), "YYYY-MM-DD") |
      | let_69        | let(n, length(prop("Tags")), n > 2 ? "many" : n > 0 ? "few" : "none")                      |
      | prop_70       | prop("Tags").filter(current != "a").length() > 0 and prop("Flag")                          |
      | prop_71       | prop("Num").add(1).multiply(2)                                                             |
      | prop_72       | prop("Name").upper().length()                                                              |
      | prop_73       | prop("Num").format().length()                                                              |
      | prop_74       | prop("When").formatDate("YYYY")                                                            |
      | prop_75       | prop("Num") == 8 and prop("Name") == "Ada Lovelace" and prop("Flag")                       |
    Then the formula properties show these values for row 1
      | name          | value      |
      | round_61      | 2.7183     |
      | max_62        | 8          |
      | min_63        | -2.5       |
      | sum_64        | 10         |
      | prop_65       | 8          |
      | if_66         | a, b, c    |
      | if_67         | 03/05/2024 |
      | formatDate_68 | 2024-03-05 |
      | let_69        | many       |
      | prop_70       | Yes        |
      | prop_71       | 18         |
      | prop_72       | 12         |
      | prop_73       | 1          |
      | prop_74       | 2024       |
      | prop_75       | Yes        |
    Then the formula properties show these values for row 2
      | name          | value      |
      | round_61      | 2.7183     |
      | max_62        | 3.75       |
      | min_63        | 1.5        |
      | sum_64        | 10         |
      | prop_65       | 1.5        |
      | if_66         |            |
      | if_67         | 01/01/2025 |
      | formatDate_68 | 2025-01-01 |
      | let_69        | few        |
      | prop_70       | No         |
      | prop_71       | 9.5        |
      | prop_72       | 6          |
      | prop_73       | 4          |
      | prop_74       | 2024       |
      | prop_75       | No         |
    Then the formula properties show these values for row 3
      | name          | value  |
      | round_61      | 2.7183 |
      | max_62        | 3      |
      | min_63        |        |
      | sum_64        | 10     |
      | prop_65       |        |
      | if_66         |        |
      | if_67         |        |
      | formatDate_68 |        |
      | let_69        | none   |
      | prop_70       | No     |
      | prop_71       | 2      |
      | prop_72       | 4      |
      | prop_73       | 0      |
      | prop_74       |        |
      | prop_75       | No     |

  Scenario: Combos type errors
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I start a new formula property
    Then these formulas show these errors
      | expression                                | error                 |
      | /* comment */ prop("Num") + 1 // trailing | Unexpected "/" [1,32] |
