@formula @formula-matrix @formula-matrix-number
Feature: Formula matrix: Number
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Number cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name            | expression                     |
      | add_1           | add(1, 2)                      |
      | subtract_2      | subtract(5, 2)                 |
      | multiply_3      | multiply(3, 4)                 |
      | divide_4        | divide(8, 2)                   |
      | mod_5           | mod(7, 3)                      |
      | pow_6           | pow(2, 10)                     |
      | abs_7           | abs(-3)                        |
      | round_8         | round(3.6)                     |
      | round_9         | round(3.14159, 2)              |
      | ceil_10         | ceil(3.2)                      |
      | floor_11        | floor(3.8)                     |
      | sqrt_12         | sqrt(16)                       |
      | cbrt_13         | cbrt(27)                       |
      | exp_14          | exp(0)                         |
      | ln_15           | ln(e())                        |
      | log10_16        | log10(1000)                    |
      | log2_17         | log2(8)                        |
      | sign_18         | sign(-5)                       |
      | min_19          | min(3, 1, 2)                   |
      | min_20          | min([3, 1, 2])                 |
      | max_21          | max(3, 1, 2)                   |
      | sum_22          | sum([1, 2, 3])                 |
      | mean_23         | mean(1, 2, 3)                  |
      | median_24       | median(1, 2, 10)               |
      | pi_25           | pi()                           |
      | e_26            | e()                            |
      | formatNumber_27 | formatNumber(1234.5, "commas") |
      | formatNumber_28 | formatNumber(0.25, "percent")  |
      | formatNumber_29 | formatNumber(1500, "usd", 2)   |
      | add_30          | add(prop("Num"), prop("Num"))  |
    Then the formula properties show these values for row 1
      | name            | value            |
      | add_1           | 3                |
      | subtract_2      | 3                |
      | multiply_3      | 12               |
      | divide_4        | 4                |
      | mod_5           | 1                |
      | pow_6           | 1024             |
      | abs_7           | 3                |
      | round_8         | 4                |
      | round_9         | 3.14             |
      | ceil_10         | 4                |
      | floor_11        | 3                |
      | sqrt_12         | 4                |
      | cbrt_13         | 3                |
      | exp_14          | 1                |
      | ln_15           | 1                |
      | log10_16        | 3                |
      | log2_17         | 3                |
      | sign_18         | -1               |
      | min_19          | 1                |
      | min_20          | 1                |
      | max_21          | 3                |
      | sum_22          | 6                |
      | mean_23         | 2                |
      | median_24       | 2                |
      | pi_25           | 3.14159265358979 |
      | e_26            | 2.71828182845905 |
      | formatNumber_27 | 1,234.5          |
      | formatNumber_28 | 25%              |
      | formatNumber_29 | $1,500.00        |
      | add_30          | 16               |
    Then the formula properties show these values for row 2
      | name            | value            |
      | add_1           | 3                |
      | subtract_2      | 3                |
      | multiply_3      | 12               |
      | divide_4        | 4                |
      | mod_5           | 1                |
      | pow_6           | 1024             |
      | abs_7           | 3                |
      | round_8         | 4                |
      | round_9         | 3.14             |
      | ceil_10         | 4                |
      | floor_11        | 3                |
      | sqrt_12         | 4                |
      | cbrt_13         | 3                |
      | exp_14          | 1                |
      | ln_15           | 1                |
      | log10_16        | 3                |
      | log2_17         | 3                |
      | sign_18         | -1               |
      | min_19          | 1                |
      | min_20          | 1                |
      | max_21          | 3                |
      | sum_22          | 6                |
      | mean_23         | 2                |
      | median_24       | 2                |
      | pi_25           | 3.14159265358979 |
      | e_26            | 2.71828182845905 |
      | formatNumber_27 | 1,234.5          |
      | formatNumber_28 | 25%              |
      | formatNumber_29 | $1,500.00        |
      | add_30          | 7.5              |
    Then the formula properties show these values for row 3
      | name            | value            |
      | add_1           | 3                |
      | subtract_2      | 3                |
      | multiply_3      | 12               |
      | divide_4        | 4                |
      | mod_5           | 1                |
      | pow_6           | 1024             |
      | abs_7           | 3                |
      | round_8         | 4                |
      | round_9         | 3.14             |
      | ceil_10         | 4                |
      | floor_11        | 3                |
      | sqrt_12         | 4                |
      | cbrt_13         | 3                |
      | exp_14          | 1                |
      | ln_15           | 1                |
      | log10_16        | 3                |
      | log2_17         | 3                |
      | sign_18         | -1               |
      | min_19          | 1                |
      | min_20          | 1                |
      | max_21          | 3                |
      | sum_22          | 6                |
      | mean_23         | 2                |
      | median_24       | 2                |
      | pi_25           | 3.14159265358979 |
      | e_26            | 2.71828182845905 |
      | formatNumber_27 | 1,234.5          |
      | formatNumber_28 | 25%              |
      | formatNumber_29 | $1,500.00        |
      | add_30          | 0                |

  Scenario: Number cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                          |
      | add_31      | add(prop("Neg"), prop("Num"))       |
      | add_32      | add(prop("Zero"), prop("Num"))      |
      | add_33      | add(2, prop("Num"))                 |
      | add_34      | add(0, prop("Num"))                 |
      | add_35      | add(-1.5, prop("Num"))              |
      | add_36      | add(prop("Num"), prop("Neg"))       |
      | add_37      | add(prop("Num"), prop("Zero"))      |
      | add_38      | add(prop("Num"), 2)                 |
      | add_39      | add(prop("Num"), 0)                 |
      | add_40      | add(prop("Num"), -1.5)              |
      | subtract_41 | subtract(prop("Num"), prop("Num"))  |
      | subtract_42 | subtract(prop("Neg"), prop("Num"))  |
      | subtract_43 | subtract(prop("Zero"), prop("Num")) |
      | subtract_44 | subtract(2, prop("Num"))            |
      | subtract_45 | subtract(0, prop("Num"))            |
      | subtract_46 | subtract(-1.5, prop("Num"))         |
      | subtract_47 | subtract(prop("Num"), prop("Neg"))  |
      | subtract_48 | subtract(prop("Num"), prop("Zero")) |
      | subtract_49 | subtract(prop("Num"), 2)            |
      | subtract_50 | subtract(prop("Num"), 0)            |
      | subtract_51 | subtract(prop("Num"), -1.5)         |
      | multiply_52 | multiply(prop("Num"), prop("Num"))  |
      | multiply_53 | multiply(prop("Neg"), prop("Num"))  |
      | multiply_54 | multiply(prop("Zero"), prop("Num")) |
      | multiply_55 | multiply(2, prop("Num"))            |
      | multiply_56 | multiply(0, prop("Num"))            |
      | multiply_57 | multiply(-1.5, prop("Num"))         |
      | multiply_58 | multiply(prop("Num"), prop("Neg"))  |
      | multiply_59 | multiply(prop("Num"), prop("Zero")) |
      | multiply_60 | multiply(prop("Num"), 2)            |
    Then the formula properties show these values for row 1
      | name        | value |
      | add_31      | 5.5   |
      | add_32      | 8     |
      | add_33      | 10    |
      | add_34      | 8     |
      | add_35      | 6.5   |
      | add_36      | 5.5   |
      | add_37      | 8     |
      | add_38      | 10    |
      | add_39      | 8     |
      | add_40      | 6.5   |
      | subtract_41 | 0     |
      | subtract_42 | -10.5 |
      | subtract_43 | -8    |
      | subtract_44 | -6    |
      | subtract_45 | -8    |
      | subtract_46 | -9.5  |
      | subtract_47 | 10.5  |
      | subtract_48 | 8     |
      | subtract_49 | 6     |
      | subtract_50 | 8     |
      | subtract_51 | 9.5   |
      | multiply_52 | 64    |
      | multiply_53 | -20   |
      | multiply_54 | 0     |
      | multiply_55 | 16    |
      | multiply_56 | 0     |
      | multiply_57 | -12   |
      | multiply_58 | -20   |
      | multiply_59 | 0     |
      | multiply_60 | 16    |
    Then the formula properties show these values for row 2
      | name        | value   |
      | add_31      | 5.25    |
      | add_32      | 10.75   |
      | add_33      | 5.75    |
      | add_34      | 3.75    |
      | add_35      | 2.25    |
      | add_36      | 5.25    |
      | add_37      | 10.75   |
      | add_38      | 5.75    |
      | add_39      | 3.75    |
      | add_40      | 2.25    |
      | subtract_41 | 0       |
      | subtract_42 | -2.25   |
      | subtract_43 | 3.25    |
      | subtract_44 | -1.75   |
      | subtract_45 | -3.75   |
      | subtract_46 | -5.25   |
      | subtract_47 | 2.25    |
      | subtract_48 | -3.25   |
      | subtract_49 | 1.75    |
      | subtract_50 | 3.75    |
      | subtract_51 | 5.25    |
      | multiply_52 | 14.0625 |
      | multiply_53 | 5.625   |
      | multiply_54 | 26.25   |
      | multiply_55 | 7.5     |
      | multiply_56 | 0       |
      | multiply_57 | -5.625  |
      | multiply_58 | 5.625   |
      | multiply_59 | 26.25   |
      | multiply_60 | 7.5     |
    Then the formula properties show these values for row 3
      | name        | value |
      | add_31      | 0     |
      | add_32      | 0     |
      | add_33      | 2     |
      | add_34      | 0     |
      | add_35      | -1.5  |
      | add_36      | 0     |
      | add_37      | 0     |
      | add_38      | 2     |
      | add_39      | 0     |
      | add_40      | -1.5  |
      | subtract_41 | 0     |
      | subtract_42 | 0     |
      | subtract_43 | 0     |
      | subtract_44 | 2     |
      | subtract_45 | 0     |
      | subtract_46 | -1.5  |
      | subtract_47 | 0     |
      | subtract_48 | 0     |
      | subtract_49 | -2    |
      | subtract_50 | 0     |
      | subtract_51 | 1.5   |
      | multiply_52 | 0     |
      | multiply_53 | 0     |
      | multiply_54 | 0     |
      | multiply_55 | 0     |
      | multiply_56 | 0     |
      | multiply_57 | 0     |
      | multiply_58 | 0     |
      | multiply_59 | 0     |
      | multiply_60 | 0     |

  Scenario: Number cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                        |
      | multiply_61 | multiply(prop("Num"), 0)          |
      | multiply_62 | multiply(prop("Num"), -1.5)       |
      | divide_63   | divide(prop("Num"), prop("Num"))  |
      | divide_64   | divide(prop("Neg"), prop("Num"))  |
      | divide_65   | divide(prop("Zero"), prop("Num")) |
      | divide_66   | divide(2, prop("Num"))            |
      | divide_67   | divide(0, prop("Num"))            |
      | divide_68   | divide(-1.5, prop("Num"))         |
      | divide_69   | divide(prop("Num"), prop("Neg"))  |
      | divide_70   | divide(prop("Num"), prop("Zero")) |
      | divide_71   | divide(prop("Num"), 2)            |
      | divide_72   | divide(prop("Num"), 0)            |
      | divide_73   | divide(prop("Num"), -1.5)         |
      | mod_74      | mod(prop("Num"), prop("Num"))     |
      | mod_75      | mod(prop("Neg"), prop("Num"))     |
      | mod_76      | mod(prop("Zero"), prop("Num"))    |
      | mod_77      | mod(2, prop("Num"))               |
      | mod_78      | mod(0, prop("Num"))               |
      | mod_79      | mod(-1.5, prop("Num"))            |
      | mod_80      | mod(prop("Num"), prop("Neg"))     |
      | mod_81      | mod(prop("Num"), prop("Zero"))    |
      | mod_82      | mod(prop("Num"), 2)               |
      | mod_83      | mod(prop("Num"), 0)               |
      | mod_84      | mod(prop("Num"), -1.5)            |
      | pow_85      | pow(prop("Num"), prop("Num"))     |
      | pow_86      | pow(prop("Neg"), prop("Num"))     |
      | pow_87      | pow(prop("Zero"), prop("Num"))    |
      | pow_88      | pow(2, prop("Num"))               |
      | pow_89      | pow(0, prop("Num"))               |
      | pow_90      | pow(-1.5, prop("Num"))            |
    Then the formula properties show these values for row 1
      | name        | value             |
      | multiply_61 | 0                 |
      | multiply_62 | -12               |
      | divide_63   | 1                 |
      | divide_64   | -0.3125           |
      | divide_65   | 0                 |
      | divide_66   | 0.25              |
      | divide_67   | 0                 |
      | divide_68   | -0.1875           |
      | divide_69   | -3.2              |
      | divide_70   |                   |
      | divide_71   | 4                 |
      | divide_72   |                   |
      | divide_73   | -5.33333333333333 |
      | mod_74      | 0                 |
      | mod_75      | -2.5              |
      | mod_76      | 0                 |
      | mod_77      | 2                 |
      | mod_78      | 0                 |
      | mod_79      | -1.5              |
      | mod_80      | 0.5               |
      | mod_81      |                   |
      | mod_82      | 0                 |
      | mod_83      |                   |
      | mod_84      | 0.5               |
      | pow_85      | 16777216          |
      | pow_86      | 1525.87890625     |
      | pow_87      | 0                 |
      | pow_88      | 256               |
      | pow_89      | 0                 |
      | pow_90      | 25.62890625       |
    Then the formula properties show these values for row 2
      | name        | value             |
      | multiply_61 | 0                 |
      | multiply_62 | -5.625            |
      | divide_63   | 1                 |
      | divide_64   | 0.4               |
      | divide_65   | 1.86666666666667  |
      | divide_66   | 0.533333333333333 |
      | divide_67   | 0                 |
      | divide_68   | -0.4              |
      | divide_69   | 2.5               |
      | divide_70   | 0.535714285714286 |
      | divide_71   | 1.875             |
      | divide_72   |                   |
      | divide_73   | -2.5              |
      | mod_74      | 0                 |
      | mod_75      | 1.5               |
      | mod_76      | 3.25              |
      | mod_77      | 2                 |
      | mod_78      | 0                 |
      | mod_79      | -1.5              |
      | mod_80      | 0.75              |
      | mod_81      | 3.75              |
      | mod_82      | 1.75              |
      | mod_83      |                   |
      | mod_84      | 0.75              |
      | pow_85      | 142.107583344775  |
      | pow_86      | 4.57448514327484  |
      | pow_87      | 1476.10635523599  |
      | pow_88      | 13.4543426440594  |
      | pow_89      | 0                 |
      | pow_90      |                   |
    Then the formula properties show these values for row 3
      | name        | value |
      | multiply_61 | 0     |
      | multiply_62 | 0     |
      | divide_63   |       |
      | divide_64   |       |
      | divide_65   |       |
      | divide_66   |       |
      | divide_67   |       |
      | divide_68   |       |
      | divide_69   |       |
      | divide_70   |       |
      | divide_71   | 0     |
      | divide_72   |       |
      | divide_73   | 0     |
      | mod_74      |       |
      | mod_75      |       |
      | mod_76      |       |
      | mod_77      |       |
      | mod_78      |       |
      | mod_79      |       |
      | mod_80      |       |
      | mod_81      |       |
      | mod_82      | 0     |
      | mod_83      |       |
      | mod_84      | 0     |
      | pow_85      | 1     |
      | pow_86      | 1     |
      | pow_87      | 1     |
      | pow_88      | 1     |
      | pow_89      | 1     |
      | pow_90      | 1     |

  Scenario: Number cases 4
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name      | expression                     |
      | pow_91    | pow(prop("Num"), prop("Neg"))  |
      | pow_92    | pow(prop("Num"), prop("Zero")) |
      | pow_93    | pow(prop("Num"), 2)            |
      | pow_94    | pow(prop("Num"), 0)            |
      | pow_95    | pow(prop("Num"), -1.5)         |
      | abs_96    | abs(prop("Num"))               |
      | abs_97    | abs(prop("Neg"))               |
      | abs_98    | abs(prop("Zero"))              |
      | abs_99    | abs(2)                         |
      | abs_100   | abs(0)                         |
      | abs_101   | abs(-1.5)                      |
      | round_102 | round(prop("Num"))             |
      | round_103 | round(prop("Neg"))             |
      | round_104 | round(prop("Zero"))            |
      | round_105 | round(2)                       |
      | round_106 | round(0)                       |
      | round_107 | round(-1.5)                    |
      | round_108 | round(prop("Num"), 1)          |
      | round_109 | round(prop("Num"), 0)          |
      | round_110 | round(prop("Num"), -1)         |
      | ceil_111  | ceil(prop("Num"))              |
      | ceil_112  | ceil(prop("Neg"))              |
      | ceil_113  | ceil(prop("Zero"))             |
      | ceil_114  | ceil(2)                        |
      | ceil_115  | ceil(0)                        |
      | ceil_116  | ceil(-1.5)                     |
      | floor_117 | floor(prop("Num"))             |
      | floor_118 | floor(prop("Neg"))             |
      | floor_119 | floor(prop("Zero"))            |
      | floor_120 | floor(2)                       |
    Then the formula properties show these values for row 1
      | name      | value              |
      | pow_91    | 0.0055242717280199 |
      | pow_92    | 1                  |
      | pow_93    | 64                 |
      | pow_94    | 1                  |
      | pow_95    | 0.0441941738241592 |
      | abs_96    | 8                  |
      | abs_97    | 2.5                |
      | abs_98    | 0                  |
      | abs_99    | 2                  |
      | abs_100   | 0                  |
      | abs_101   | 1.5                |
      | round_102 | 8                  |
      | round_103 | -2                 |
      | round_104 | 0                  |
      | round_105 | 2                  |
      | round_106 | 0                  |
      | round_107 | -1                 |
      | round_108 | 8                  |
      | round_109 | 8                  |
      | round_110 | 8                  |
      | ceil_111  | 8                  |
      | ceil_112  | -2                 |
      | ceil_113  | 0                  |
      | ceil_114  | 2                  |
      | ceil_115  | 0                  |
      | ceil_116  | -1                 |
      | floor_117 | 8                  |
      | floor_118 | -3                 |
      | floor_119 | 0                  |
      | floor_120 | 2                  |
    Then the formula properties show these values for row 2
      | name      | value             |
      | pow_91    | 7.26184377413891  |
      | pow_92    | 10428.4286499023  |
      | pow_93    | 14.0625           |
      | pow_94    | 1                 |
      | pow_95    | 0.137706074531819 |
      | abs_96    | 3.75              |
      | abs_97    | 1.5               |
      | abs_98    | 7                 |
      | abs_99    | 2                 |
      | abs_100   | 0                 |
      | abs_101   | 1.5               |
      | round_102 | 4                 |
      | round_103 | 2                 |
      | round_104 | 7                 |
      | round_105 | 2                 |
      | round_106 | 0                 |
      | round_107 | -1                |
      | round_108 | 3.8               |
      | round_109 | 4                 |
      | round_110 | 4                 |
      | ceil_111  | 4                 |
      | ceil_112  | 2                 |
      | ceil_113  | 7                 |
      | ceil_114  | 2                 |
      | ceil_115  | 0                 |
      | ceil_116  | -1                |
      | floor_117 | 3                 |
      | floor_118 | 1                 |
      | floor_119 | 7                 |
      | floor_120 | 2                 |
    Then the formula properties show these values for row 3
      | name      | value |
      | pow_91    | 1     |
      | pow_92    | 1     |
      | pow_93    | 0     |
      | pow_94    | 1     |
      | pow_95    |       |
      | abs_96    |       |
      | abs_97    |       |
      | abs_98    |       |
      | abs_99    | 2     |
      | abs_100   | 0     |
      | abs_101   | 1.5   |
      | round_102 |       |
      | round_103 |       |
      | round_104 |       |
      | round_105 | 2     |
      | round_106 | 0     |
      | round_107 | -1    |
      | round_108 |       |
      | round_109 |       |
      | round_110 |       |
      | ceil_111  |       |
      | ceil_112  |       |
      | ceil_113  |       |
      | ceil_114  | 2     |
      | ceil_115  | 0     |
      | ceil_116  | -1    |
      | floor_117 |       |
      | floor_118 |       |
      | floor_119 |       |
      | floor_120 | 2     |

  Scenario: Number cases 5
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name      | expression          |
      | floor_121 | floor(0)            |
      | floor_122 | floor(-1.5)         |
      | sqrt_123  | sqrt(prop("Num"))   |
      | sqrt_124  | sqrt(prop("Neg"))   |
      | sqrt_125  | sqrt(prop("Zero"))  |
      | sqrt_126  | sqrt(2)             |
      | sqrt_127  | sqrt(0)             |
      | sqrt_128  | sqrt(-1.5)          |
      | cbrt_129  | cbrt(prop("Num"))   |
      | cbrt_130  | cbrt(prop("Neg"))   |
      | cbrt_131  | cbrt(prop("Zero"))  |
      | cbrt_132  | cbrt(2)             |
      | cbrt_133  | cbrt(0)             |
      | cbrt_134  | cbrt(-1.5)          |
      | exp_135   | exp(prop("Num"))    |
      | exp_136   | exp(prop("Neg"))    |
      | exp_137   | exp(prop("Zero"))   |
      | exp_138   | exp(2)              |
      | exp_139   | exp(-1.5)           |
      | ln_140    | ln(prop("Num"))     |
      | ln_141    | ln(prop("Neg"))     |
      | ln_142    | ln(prop("Zero"))    |
      | ln_143    | ln(2)               |
      | ln_144    | ln(0)               |
      | ln_145    | ln(-1.5)            |
      | log10_146 | log10(prop("Num"))  |
      | log10_147 | log10(prop("Neg"))  |
      | log10_148 | log10(prop("Zero")) |
      | log10_149 | log10(2)            |
      | log10_150 | log10(0)            |
    Then the formula properties show these values for row 1
      | name      | value              |
      | floor_121 | 0                  |
      | floor_122 | -2                 |
      | sqrt_123  | 2.82842712474619   |
      | sqrt_124  |                    |
      | sqrt_125  | 0                  |
      | sqrt_126  | 1.4142135623731    |
      | sqrt_127  | 0                  |
      | sqrt_128  |                    |
      | cbrt_129  | 2                  |
      | cbrt_130  | -1.35720880829745  |
      | cbrt_131  | 0                  |
      | cbrt_132  | 1.25992104989487   |
      | cbrt_133  | 0                  |
      | cbrt_134  | -1.14471424255333  |
      | exp_135   | 2980.95798704173   |
      | exp_136   | 0.0820849986238988 |
      | exp_137   | 1                  |
      | exp_138   | 7.38905609893065   |
      | exp_139   | 0.22313016014843   |
      | ln_140    | 2.07944154167984   |
      | ln_141    |                    |
      | ln_142    |                    |
      | ln_143    | 0.693147180559945  |
      | ln_144    |                    |
      | ln_145    |                    |
      | log10_146 | 0.903089986991944  |
      | log10_147 |                    |
      | log10_148 |                    |
      | log10_149 | 0.301029995663981  |
      | log10_150 |                    |
    Then the formula properties show these values for row 2
      | name      | value             |
      | floor_121 | 0                 |
      | floor_122 | -2                |
      | sqrt_123  | 1.93649167310371  |
      | sqrt_124  | 1.22474487139159  |
      | sqrt_125  | 2.64575131106459  |
      | sqrt_126  | 1.4142135623731   |
      | sqrt_127  | 0                 |
      | sqrt_128  |                   |
      | cbrt_129  | 1.55361625297693  |
      | cbrt_130  | 1.14471424255333  |
      | cbrt_131  | 1.91293118277239  |
      | cbrt_132  | 1.25992104989487  |
      | cbrt_133  | 0                 |
      | cbrt_134  | -1.14471424255333 |
      | exp_135   | 42.5210820000628  |
      | exp_136   | 4.48168907033806  |
      | exp_137   | 1096.63315842846  |
      | exp_138   | 7.38905609893065  |
      | exp_139   | 0.22313016014843  |
      | ln_140    | 1.32175583998232  |
      | ln_141    | 0.405465108108164 |
      | ln_142    | 1.94591014905531  |
      | ln_143    | 0.693147180559945 |
      | ln_144    |                   |
      | ln_145    |                   |
      | log10_146 | 0.574031267727719 |
      | log10_147 | 0.176091259055681 |
      | log10_148 | 0.845098040014257 |
      | log10_149 | 0.301029995663981 |
      | log10_150 |                   |
    Then the formula properties show these values for row 3
      | name      | value             |
      | floor_121 | 0                 |
      | floor_122 | -2                |
      | sqrt_123  |                   |
      | sqrt_124  |                   |
      | sqrt_125  |                   |
      | sqrt_126  | 1.4142135623731   |
      | sqrt_127  | 0                 |
      | sqrt_128  |                   |
      | cbrt_129  |                   |
      | cbrt_130  |                   |
      | cbrt_131  |                   |
      | cbrt_132  | 1.25992104989487  |
      | cbrt_133  | 0                 |
      | cbrt_134  | -1.14471424255333 |
      | exp_135   |                   |
      | exp_136   |                   |
      | exp_137   |                   |
      | exp_138   | 7.38905609893065  |
      | exp_139   | 0.22313016014843  |
      | ln_140    |                   |
      | ln_141    |                   |
      | ln_142    |                   |
      | ln_143    | 0.693147180559945 |
      | ln_144    |                   |
      | ln_145    |                   |
      | log10_146 |                   |
      | log10_147 |                   |
      | log10_148 |                   |
      | log10_149 | 0.301029995663981 |
      | log10_150 |                   |

  Scenario: Number cases 6
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name      | expression                                  |
      | log10_151 | log10(-1.5)                                 |
      | log2_152  | log2(prop("Num"))                           |
      | log2_153  | log2(prop("Neg"))                           |
      | log2_154  | log2(prop("Zero"))                          |
      | log2_155  | log2(2)                                     |
      | log2_156  | log2(0)                                     |
      | log2_157  | log2(-1.5)                                  |
      | sign_158  | sign(prop("Num"))                           |
      | sign_159  | sign(prop("Neg"))                           |
      | sign_160  | sign(prop("Zero"))                          |
      | sign_161  | sign(2)                                     |
      | sign_162  | sign(0)                                     |
      | sign_163  | sign(-1.5)                                  |
      | min_164   | min(prop("Num"))                            |
      | min_165   | min(prop("Neg"))                            |
      | min_166   | min(prop("Zero"))                           |
      | min_167   | min(2)                                      |
      | min_168   | min(0)                                      |
      | min_169   | min(-1.5)                                   |
      | min_170   | min([1, 2, 3])                              |
      | min_171   | min([])                                     |
      | min_172   | min(prop("Num"), prop("Neg"))               |
      | min_173   | min(prop("Num"), prop("Neg"), prop("Zero")) |
      | min_174   | min(prop("Num"), prop("Zero"))              |
      | max_175   | max(prop("Num"))                            |
      | max_176   | max(prop("Neg"))                            |
      | max_177   | max(prop("Zero"))                           |
      | max_178   | max(2)                                      |
      | max_179   | max(0)                                      |
      | max_180   | max(-1.5)                                   |
    Then the formula properties show these values for row 1
      | name      | value |
      | log10_151 |       |
      | log2_152  | 3     |
      | log2_153  |       |
      | log2_154  |       |
      | log2_155  | 1     |
      | log2_156  |       |
      | log2_157  |       |
      | sign_158  | 1     |
      | sign_159  | -1    |
      | sign_160  | 0     |
      | sign_161  | 1     |
      | sign_162  | 0     |
      | sign_163  | -1    |
      | min_164   | 8     |
      | min_165   | -2.5  |
      | min_166   | 0     |
      | min_167   | 2     |
      | min_168   | 0     |
      | min_169   | -1.5  |
      | min_170   | 1     |
      | min_171   |       |
      | min_172   | -2.5  |
      | min_173   | -2.5  |
      | min_174   | 0     |
      | max_175   | 8     |
      | max_176   | -2.5  |
      | max_177   | 0     |
      | max_178   | 2     |
      | max_179   | 0     |
      | max_180   | -1.5  |
    Then the formula properties show these values for row 2
      | name      | value             |
      | log10_151 |                   |
      | log2_152  | 1.90689059560852  |
      | log2_153  | 0.584962500721156 |
      | log2_154  | 2.8073549220576   |
      | log2_155  | 1                 |
      | log2_156  |                   |
      | log2_157  |                   |
      | sign_158  | 1                 |
      | sign_159  | 1                 |
      | sign_160  | 1                 |
      | sign_161  | 1                 |
      | sign_162  | 0                 |
      | sign_163  | -1                |
      | min_164   | 3.75              |
      | min_165   | 1.5               |
      | min_166   | 7                 |
      | min_167   | 2                 |
      | min_168   | 0                 |
      | min_169   | -1.5              |
      | min_170   | 1                 |
      | min_171   |                   |
      | min_172   | 1.5               |
      | min_173   | 1.5               |
      | min_174   | 3.75              |
      | max_175   | 3.75              |
      | max_176   | 1.5               |
      | max_177   | 7                 |
      | max_178   | 2                 |
      | max_179   | 0                 |
      | max_180   | -1.5              |
    Then the formula properties show these values for row 3
      | name      | value |
      | log10_151 |       |
      | log2_152  |       |
      | log2_153  |       |
      | log2_154  |       |
      | log2_155  | 1     |
      | log2_156  |       |
      | log2_157  |       |
      | sign_158  |       |
      | sign_159  |       |
      | sign_160  |       |
      | sign_161  | 1     |
      | sign_162  | 0     |
      | sign_163  | -1    |
      | min_164   |       |
      | min_165   |       |
      | min_166   |       |
      | min_167   | 2     |
      | min_168   | 0     |
      | min_169   | -1.5  |
      | min_170   | 1     |
      | min_171   |       |
      | min_172   |       |
      | min_173   |       |
      | min_174   |       |
      | max_175   |       |
      | max_176   |       |
      | max_177   |       |
      | max_178   | 2     |
      | max_179   | 0     |
      | max_180   | -1.5  |

  Scenario: Number cases 7
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name       | expression                                   |
      | max_181    | max([1, 2, 3])                               |
      | max_182    | max([])                                      |
      | max_183    | max(prop("Num"), prop("Neg"))                |
      | max_184    | max(prop("Num"), prop("Neg"), prop("Zero"))  |
      | max_185    | max(prop("Num"), prop("Zero"))               |
      | sum_186    | sum(prop("Num"))                             |
      | sum_187    | sum(prop("Neg"))                             |
      | sum_188    | sum(prop("Zero"))                            |
      | sum_189    | sum(2)                                       |
      | sum_190    | sum(0)                                       |
      | sum_191    | sum(-1.5)                                    |
      | sum_192    | sum([])                                      |
      | sum_193    | sum(prop("Num"), prop("Neg"))                |
      | sum_194    | sum(prop("Num"), prop("Neg"), prop("Zero"))  |
      | sum_195    | sum(prop("Num"), prop("Zero"))               |
      | mean_196   | mean(prop("Num"))                            |
      | mean_197   | mean(prop("Neg"))                            |
      | mean_198   | mean(prop("Zero"))                           |
      | mean_199   | mean(2)                                      |
      | mean_200   | mean(0)                                      |
      | mean_201   | mean(-1.5)                                   |
      | mean_202   | mean([1, 2, 3])                              |
      | mean_203   | mean([])                                     |
      | mean_204   | mean(prop("Num"), prop("Neg"))               |
      | mean_205   | mean(prop("Num"), prop("Neg"), prop("Zero")) |
      | mean_206   | mean(prop("Num"), prop("Zero"))              |
      | median_207 | median(prop("Num"))                          |
      | median_208 | median(prop("Neg"))                          |
      | median_209 | median(prop("Zero"))                         |
      | median_210 | median(2)                                    |
    Then the formula properties show these values for row 1
      | name       | value            |
      | max_181    | 3                |
      | max_182    |                  |
      | max_183    | 8                |
      | max_184    | 8                |
      | max_185    | 8                |
      | sum_186    | 8                |
      | sum_187    | -2.5             |
      | sum_188    | 0                |
      | sum_189    | 2                |
      | sum_190    | 0                |
      | sum_191    | -1.5             |
      | sum_192    | 0                |
      | sum_193    | 5.5              |
      | sum_194    | 5.5              |
      | sum_195    | 8                |
      | mean_196   | 8                |
      | mean_197   | -2.5             |
      | mean_198   | 0                |
      | mean_199   | 2                |
      | mean_200   | 0                |
      | mean_201   | -1.5             |
      | mean_202   | 2                |
      | mean_203   |                  |
      | mean_204   | 2.75             |
      | mean_205   | 1.83333333333333 |
      | mean_206   | 4                |
      | median_207 | 8                |
      | median_208 | -2.5             |
      | median_209 | 0                |
      | median_210 | 2                |
    Then the formula properties show these values for row 2
      | name       | value            |
      | max_181    | 3                |
      | max_182    |                  |
      | max_183    | 3.75             |
      | max_184    | 7                |
      | max_185    | 7                |
      | sum_186    | 3.75             |
      | sum_187    | 1.5              |
      | sum_188    | 7                |
      | sum_189    | 2                |
      | sum_190    | 0                |
      | sum_191    | -1.5             |
      | sum_192    | 0                |
      | sum_193    | 5.25             |
      | sum_194    | 12.25            |
      | sum_195    | 10.75            |
      | mean_196   | 3.75             |
      | mean_197   | 1.5              |
      | mean_198   | 7                |
      | mean_199   | 2                |
      | mean_200   | 0                |
      | mean_201   | -1.5             |
      | mean_202   | 2                |
      | mean_203   |                  |
      | mean_204   | 2.625            |
      | mean_205   | 4.08333333333333 |
      | mean_206   | 5.375            |
      | median_207 | 3.75             |
      | median_208 | 1.5              |
      | median_209 | 7                |
      | median_210 | 2                |
    Then the formula properties show these values for row 3
      | name       | value |
      | max_181    | 3     |
      | max_182    |       |
      | max_183    |       |
      | max_184    |       |
      | max_185    |       |
      | sum_186    | 0     |
      | sum_187    | 0     |
      | sum_188    | 0     |
      | sum_189    | 2     |
      | sum_190    | 0     |
      | sum_191    | -1.5  |
      | sum_192    | 0     |
      | sum_193    | 0     |
      | sum_194    | 0     |
      | sum_195    | 0     |
      | mean_196   |       |
      | mean_197   |       |
      | mean_198   |       |
      | mean_199   | 2     |
      | mean_200   | 0     |
      | mean_201   | -1.5  |
      | mean_202   | 2     |
      | mean_203   |       |
      | mean_204   |       |
      | mean_205   |       |
      | mean_206   |       |
      | median_207 |       |
      | median_208 |       |
      | median_209 |       |
      | median_210 | 2     |

  Scenario: Number cases 8
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name             | expression                                        |
      | median_211       | median(0)                                         |
      | median_212       | median(-1.5)                                      |
      | median_213       | median([1, 2, 3])                                 |
      | median_214       | median([])                                        |
      | median_215       | median(prop("Num"), prop("Neg"))                  |
      | median_216       | median(prop("Num"), prop("Neg"), prop("Zero"))    |
      | median_217       | median(prop("Num"), prop("Zero"))                 |
      | formatNumber_218 | formatNumber(prop("Num"), "commas")               |
      | formatNumber_219 | formatNumber(prop("Neg"), "commas")               |
      | formatNumber_220 | formatNumber(prop("Zero"), "commas")              |
      | formatNumber_221 | formatNumber(2, "commas")                         |
      | formatNumber_222 | formatNumber(0, "commas")                         |
      | formatNumber_223 | formatNumber(-1.5, "commas")                      |
      | formatNumber_224 | formatNumber(prop("Num"), "percent")              |
      | formatNumber_225 | formatNumber(prop("Num"), "USD")                  |
      | formatNumber_226 | formatNumber(prop("Num"), "EUR")                  |
      | formatNumber_227 | formatNumber(prop("Num"), "commas", prop("Num"))  |
      | formatNumber_228 | formatNumber(prop("Num"), "commas", prop("Neg"))  |
      | formatNumber_229 | formatNumber(prop("Num"), "commas", prop("Zero")) |
      | formatNumber_230 | formatNumber(prop("Num"), "commas", 2)            |
      | formatNumber_231 | formatNumber(prop("Num"), "commas", 0)            |
      | formatNumber_232 | formatNumber(prop("Num"), "commas", -1.5)         |
    Then the formula properties show these values for row 1
      | name             | value      |
      | median_211       | 0          |
      | median_212       | -1.5       |
      | median_213       | 2          |
      | median_214       |            |
      | median_215       | 2.75       |
      | median_216       | 0          |
      | median_217       | 4          |
      | formatNumber_218 | 8          |
      | formatNumber_219 | -2.5       |
      | formatNumber_220 | 0          |
      | formatNumber_221 | 2          |
      | formatNumber_222 | 0          |
      | formatNumber_223 | -1.5       |
      | formatNumber_224 | 800%       |
      | formatNumber_225 | $8.00      |
      | formatNumber_226 | €8.00      |
      | formatNumber_227 | 8.00000000 |
      | formatNumber_228 | 8          |
      | formatNumber_229 | 8          |
      | formatNumber_230 | 8.00       |
      | formatNumber_231 | 8          |
      | formatNumber_232 | 8          |
    Then the formula properties show these values for row 2
      | name             | value     |
      | median_211       | 0         |
      | median_212       | -1.5      |
      | median_213       | 2         |
      | median_214       |           |
      | median_215       | 2.625     |
      | median_216       | 3.75      |
      | median_217       | 5.375     |
      | formatNumber_218 | 3.75      |
      | formatNumber_219 | 1.5       |
      | formatNumber_220 | 7         |
      | formatNumber_221 | 2         |
      | formatNumber_222 | 0         |
      | formatNumber_223 | -1.5      |
      | formatNumber_224 | 375%      |
      | formatNumber_225 | $3.75     |
      | formatNumber_226 | €3.75     |
      | formatNumber_227 | 3.750     |
      | formatNumber_228 | 3.8       |
      | formatNumber_229 | 3.7500000 |
      | formatNumber_230 | 3.75      |
      | formatNumber_231 | 4         |
      | formatNumber_232 | 4         |
    Then the formula properties show these values for row 3
      | name             | value |
      | median_211       | 0     |
      | median_212       | -1.5  |
      | median_213       | 2     |
      | median_214       |       |
      | median_215       |       |
      | median_216       |       |
      | median_217       |       |
      | formatNumber_218 |       |
      | formatNumber_219 |       |
      | formatNumber_220 |       |
      | formatNumber_221 | 2     |
      | formatNumber_222 | 0     |
      | formatNumber_223 | -1.5  |
      | formatNumber_224 |       |
      | formatNumber_225 |       |
      | formatNumber_226 |       |
      | formatNumber_227 |       |
      | formatNumber_228 |       |
      | formatNumber_229 |       |
      | formatNumber_230 |       |
      | formatNumber_231 |       |
      | formatNumber_232 |       |

  Scenario: Number type errors
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I start a new formula property
    Then these formulas show these errors
      | expression                   | error                                                                      |
      | min(prop("Tags"))            | min() expects number or list<number> for "values", got list<text> [1,5]    |
      | min(["b", "a", "c", "a"])    | min() expects number or list<number> for "values", got list<text> [1,5]    |
      | max(prop("Tags"))            | max() expects number or list<number> for "values", got list<text> [1,5]    |
      | max(["b", "a", "c", "a"])    | max() expects number or list<number> for "values", got list<text> [1,5]    |
      | sum(prop("Tags"))            | sum() expects number or list<number> for "values", got list<text> [1,5]    |
      | sum(["b", "a", "c", "a"])    | sum() expects number or list<number> for "values", got list<text> [1,5]    |
      | mean(prop("Tags"))           | mean() expects number or list<number> for "values", got list<text> [1,6]   |
      | mean(["b", "a", "c", "a"])   | mean() expects number or list<number> for "values", got list<text> [1,6]   |
      | median(prop("Tags"))         | median() expects number or list<number> for "values", got list<text> [1,8] |
      | median(["b", "a", "c", "a"]) | median() expects number or list<number> for "values", got list<text> [1,8] |
