@formula @formula-matrix @formula-matrix-operators
Feature: Formula matrix: Operators
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Operators cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                         |
      | _1          | 3 + 2                              |
      | _2          | "Hello" + " " + "world"            |
      | _3          | 5 - 2                              |
      | _4          | 3 * 4                              |
      | _5          | 8 / 2                              |
      | _6          | 7 % 3                              |
      | _7          | 2 ^ 10                             |
      | _8          | "a" == "a"                         |
      | _9          | 1 != 2                             |
      | _10         | 3 > 2                              |
      | _11         | 2 >= 2                             |
      | _12         | 1 <= 2                             |
      | _13         | prop("Flag") ? "Complete" : "Open" |
      | true_14     | true                               |
      | false_15    | false                              |
      | index_16    | ["a", "b"].map(index)              |
      | prop_17     | prop("Num") + prop("Neg")          |
      | prop_18     | prop("Num") + prop("Zero")         |
      | prop_19     | prop("Zero") + 1                   |
      | prop_20     | prop("Num") - prop("Neg")          |
      | prop_21     | prop("Num") * prop("Neg")          |
      | prop_22     | prop("Num") / prop("Zero")         |
      | prop_23     | prop("Zero") / prop("Num")         |
      | prop_24     | prop("Num") / 4                    |
      | operator_25 | 7 / 2                              |
      | operator_26 | 1 / 3                              |
      | operator_27 | 2 / 3                              |
      | operator_28 | 10 / 4 * 2                         |
      | operator_29 | -prop("Neg")                       |
      | operator_30 | -prop("Zero")                      |
    Then the formula properties show these values for row 1
      | name        | value             |
      | _1          | 5                 |
      | _2          | Hello world       |
      | _3          | 3                 |
      | _4          | 12                |
      | _5          | 4                 |
      | _6          | 1                 |
      | _7          | 1024              |
      | _8          | Yes               |
      | _9          | Yes               |
      | _10         | Yes               |
      | _11         | Yes               |
      | _12         | Yes               |
      | _13         | Complete          |
      | true_14     | Yes               |
      | false_15    | No                |
      | index_16    | 0, 1              |
      | prop_17     | 5.5               |
      | prop_18     | 8                 |
      | prop_19     | 1                 |
      | prop_20     | 10.5              |
      | prop_21     | -20               |
      | prop_22     |                   |
      | prop_23     | 0                 |
      | prop_24     | 2                 |
      | operator_25 | 3.5               |
      | operator_26 | 0.333333333333333 |
      | operator_27 | 0.666666666666667 |
      | operator_28 | 5                 |
      | operator_29 | 2.5               |
      | operator_30 | 0                 |
    Then the formula properties show these values for row 2
      | name        | value             |
      | _1          | 5                 |
      | _2          | Hello world       |
      | _3          | 3                 |
      | _4          | 12                |
      | _5          | 4                 |
      | _6          | 1                 |
      | _7          | 1024              |
      | _8          | Yes               |
      | _9          | Yes               |
      | _10         | Yes               |
      | _11         | Yes               |
      | _12         | Yes               |
      | _13         | Open              |
      | true_14     | Yes               |
      | false_15    | No                |
      | index_16    | 0, 1              |
      | prop_17     | 5.25              |
      | prop_18     | 10.75             |
      | prop_19     | 8                 |
      | prop_20     | 2.25              |
      | prop_21     | 5.625             |
      | prop_22     | 0.535714285714286 |
      | prop_23     | 1.86666666666667  |
      | prop_24     | 0.9375            |
      | operator_25 | 3.5               |
      | operator_26 | 0.333333333333333 |
      | operator_27 | 0.666666666666667 |
      | operator_28 | 5                 |
      | operator_29 | -1.5              |
      | operator_30 | -7                |
    Then the formula properties show these values for row 3
      | name        | value             |
      | _1          | 5                 |
      | _2          | Hello world       |
      | _3          | 3                 |
      | _4          | 12                |
      | _5          | 4                 |
      | _6          | 1                 |
      | _7          | 1024              |
      | _8          | Yes               |
      | _9          | Yes               |
      | _10         | Yes               |
      | _11         | Yes               |
      | _12         | Yes               |
      | _13         | Open              |
      | true_14     | Yes               |
      | false_15    | No                |
      | index_16    | 0, 1              |
      | prop_17     |                   |
      | prop_18     |                   |
      | prop_19     | 1                 |
      | prop_20     | 0                 |
      | prop_21     | 0                 |
      | prop_22     |                   |
      | prop_23     |                   |
      | prop_24     | 0                 |
      | operator_25 | 3.5               |
      | operator_26 | 0.333333333333333 |
      | operator_27 | 0.666666666666667 |
      | operator_28 | 5                 |
      | operator_29 |                   |
      | operator_30 |                   |

  Scenario: Operators cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                        |
      | prop_31     | prop("Num") % 3                   |
      | prop_32     | prop("Neg") % 2                   |
      | operator_33 | -7 % 3                            |
      | operator_34 | 7 % -3                            |
      | operator_35 | 2 ^ 0.5                           |
      | prop_36     | prop("Num") ^ 2                   |
      | operator_37 | 2 ^ 3 ^ 2                         |
      | operator_38 | (2 ^ 3) ^ 2                       |
      | operator_39 | 1 + 2 * 3                         |
      | operator_40 | (1 + 2) * 3                       |
      | operator_41 | 8 / 2 / 2                         |
      | operator_42 | 10 - 2 - 3                        |
      | operator_43 | 1 + 2 == 3                        |
      | operator_44 | "a" + "b"                         |
      | prop_45     | prop("Name") + " " + prop("Note") |
      | prop_46     | prop("Name") + prop("Note")       |
      | operator_47 | "" + ""                           |
      | prop_48     | prop("Num") == 8                  |
      | prop_49     | prop("Num") != 8                  |
      | prop_50     | prop("Num") > prop("Neg")         |
      | prop_51     | prop("Num") >= 8                  |
      | prop_52     | prop("Num") < 8                   |
      | prop_53     | prop("Num") <= prop("Zero")       |
      | prop_54     | prop("Name") == "Ada Lovelace"    |
      | prop_55     | prop("Name") != "notion"          |
      | operator_56 | "b" > "a"                         |
      | operator_57 | "B" > "a"                         |
      | operator_58 | "abc" < "abd"                     |
      | prop_59     | prop("Flag") == true              |
      | prop_60     | prop("Flag") != false             |
    Then the formula properties show these values for row 1
      | name        | value                      |
      | prop_31     | 2                          |
      | prop_32     | -0.5                       |
      | operator_33 | -1                         |
      | operator_34 | 1                          |
      | operator_35 | 1.4142135623731            |
      | prop_36     | 64                         |
      | operator_37 | 512                        |
      | operator_38 | 64                         |
      | operator_39 | 7                          |
      | operator_40 | 9                          |
      | operator_41 | 2                          |
      | operator_42 | 5                          |
      | operator_43 | Yes                        |
      | operator_44 | ab                         |
      | prop_45     | Ada Lovelace Hello, World! |
      | prop_46     | Ada LovelaceHello, World!  |
      | operator_47 |                            |
      | prop_48     | Yes                        |
      | prop_49     | No                         |
      | prop_50     | Yes                        |
      | prop_51     | Yes                        |
      | prop_52     | No                         |
      | prop_53     | No                         |
      | prop_54     | Yes                        |
      | prop_55     | Yes                        |
      | operator_56 | Yes                        |
      | operator_57 | Yes                        |
      | operator_58 | Yes                        |
      | prop_59     | Yes                        |
      | prop_60     | Yes                        |
    Then the formula properties show these values for row 2
      | name        | value           |
      | prop_31     | 0.75            |
      | prop_32     | 1.5             |
      | operator_33 | -1              |
      | operator_34 | 1               |
      | operator_35 | 1.4142135623731 |
      | prop_36     | 14.0625         |
      | operator_37 | 512             |
      | operator_38 | 64              |
      | operator_39 | 7               |
      | operator_40 | 9               |
      | operator_41 | 2               |
      | operator_42 | 5               |
      | operator_43 | Yes             |
      | operator_44 | ab              |
      | prop_45     | notion x        |
      | prop_46     | notionx         |
      | operator_47 |                 |
      | prop_48     | No              |
      | prop_49     | Yes             |
      | prop_50     | Yes             |
      | prop_51     | No              |
      | prop_52     | Yes             |
      | prop_53     | Yes             |
      | prop_54     | No              |
      | prop_55     | No              |
      | operator_56 | Yes             |
      | operator_57 | Yes             |
      | operator_58 | Yes             |
      | prop_59     | No              |
      | prop_60     | No              |
    Then the formula properties show these values for row 3
      | name        | value           |
      | prop_31     | 0               |
      | prop_32     | 0               |
      | operator_33 | -1              |
      | operator_34 | 1               |
      | operator_35 | 1.4142135623731 |
      | prop_36     | 0               |
      | operator_37 | 512             |
      | operator_38 | 64              |
      | operator_39 | 7               |
      | operator_40 | 9               |
      | operator_41 | 2               |
      | operator_42 | 5               |
      | operator_43 | Yes             |
      | operator_44 | ab              |
      | prop_45     | Row3            |
      | prop_46     | Row3            |
      | operator_47 |                 |
      | prop_48     | No              |
      | prop_49     | Yes             |
      | prop_50     | No              |
      | prop_51     | No              |
      | prop_52     | No              |
      | prop_53     | No              |
      | prop_54     | No              |
      | prop_55     | Yes             |
      | operator_56 | Yes             |
      | operator_57 | Yes             |
      | operator_58 | Yes             |
      | prop_59     | No              |
      | prop_60     | No              |

  Scenario: Operators cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                                         |
      | operator_61 | true == false                                      |
      | prop_62     | prop("When") == parseDate("2024-03-05")            |
      | prop_63     | prop("When") > parseDate("2024-06-01")             |
      | prop_64     | prop("When") < parseDate("2024-06-01")             |
      | prop_65     | prop("Tags") == ["a", "b", "c"]                    |
      | prop_66     | prop("Tags") != []                                 |
      | prop_67     | prop("Flag") and prop("Num") > 5                   |
      | prop_68     | prop("Flag") or prop("Num") > 5                    |
      | operator_69 | not prop("Flag")                                   |
      | operator_70 | not empty(prop("Note"))                            |
      | operator_71 | true and false or true                             |
      | operator_72 | true or false and false                            |
      | operator_73 | not true and false                                 |
      | prop_74     | prop("Num") > 5 ? "big" : "small"                  |
      | prop_75     | prop("Num") > 5 and prop("Neg") < 0 ? "yes" : "no" |
      | operator_76 | (prop("Num") + prop("Neg")) * 2 ^ 2 - 1            |
    Then the formula properties show these values for row 1
      | name        | value |
      | operator_61 | No    |
      | prop_62     | Yes   |
      | prop_63     | No    |
      | prop_64     | Yes   |
      | prop_65     | Yes   |
      | prop_66     | Yes   |
      | prop_67     | Yes   |
      | prop_68     | Yes   |
      | operator_69 | No    |
      | operator_70 | Yes   |
      | operator_71 | Yes   |
      | operator_72 | Yes   |
      | operator_73 | No    |
      | prop_74     | big   |
      | prop_75     | yes   |
      | operator_76 | 21    |
    Then the formula properties show these values for row 2
      | name        | value |
      | operator_61 | No    |
      | prop_62     | No    |
      | prop_63     | Yes   |
      | prop_64     | No    |
      | prop_65     | No    |
      | prop_66     | Yes   |
      | prop_67     | No    |
      | prop_68     | No    |
      | operator_69 | Yes   |
      | operator_70 | Yes   |
      | operator_71 | Yes   |
      | operator_72 | Yes   |
      | operator_73 | No    |
      | prop_74     | small |
      | prop_75     | no    |
      | operator_76 | 20    |
    Then the formula properties show these values for row 3
      | name        | value |
      | operator_61 | No    |
      | prop_62     | No    |
      | prop_63     | No    |
      | prop_64     | No    |
      | prop_65     | No    |
      | prop_66     | No    |
      | prop_67     | No    |
      | prop_68     | No    |
      | operator_69 | Yes   |
      | operator_70 | No    |
      | operator_71 | Yes   |
      | operator_72 | Yes   |
      | operator_73 | No    |
      | prop_74     | small |
      | prop_75     | no    |
      | operator_76 | -1    |
