@formula @formula-matrix @formula-matrix-list
Feature: Formula matrix: List
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: List cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression                       |
      | at_1         | [1, 2, 3].at(1)                  |
      | first_2      | first([1, 2, 3])                 |
      | last_3       | last([1, 2, 3])                  |
      | slice_4      | [1, 2, 3].slice(1)               |
      | concat_5     | concat([1], [2, 3])              |
      | sort_6       | sort([3, 1, 2])                  |
      | reverse_7    | reverse([1, 2, 3])               |
      | unique_8     | unique([1, 1, 2])                |
      | includes_9   | ["a", "b"].includes("a")         |
      | flat_10      | flat([[1, 2], [3]])              |
      | map_11       | [1, 2, 3].map(current * 2)       |
      | filter_12    | [1, 2, 3].filter(current > 1)    |
      | find_13      | [1, 2, 3].find(current > 1)      |
      | findIndex_14 | [1, 2, 3].findIndex(current > 1) |
      | some_15      | [1, 2, 3].some(current > 2)      |
      | every_16     | [1, 2, 3].every(current > 0)     |
      | at_17        | at(prop("Tags"), 0)              |
      | at_18        | at([1, 2, 3], 0)                 |
      | at_19        | at(["b", "a", "c", "a"], 0)      |
      | at_20        | at([], 0)                        |
      | at_21        | at(prop("Tags"), 2)              |
      | at_22        | at(prop("Tags"), -1)             |
      | at_23        | at(prop("Tags"), 10)             |
      | first_24     | first(prop("Tags"))              |
      | first_25     | first(["b", "a", "c", "a"])      |
      | first_26     | first([])                        |
      | last_27      | last(prop("Tags"))               |
      | last_28      | last(["b", "a", "c", "a"])       |
      | last_29      | last([])                         |
      | slice_30     | slice(prop("Tags"), 1)           |
    Then the formula properties show these values for row 1
      | name         | value   |
      | at_1         | 2       |
      | first_2      | 1       |
      | last_3       | 3       |
      | slice_4      | 2, 3    |
      | concat_5     | 1, 2, 3 |
      | sort_6       | 1, 2, 3 |
      | reverse_7    | 3, 2, 1 |
      | unique_8     | 1, 2    |
      | includes_9   | Yes     |
      | flat_10      | 1, 2, 3 |
      | map_11       | 2, 4, 6 |
      | filter_12    | 2, 3    |
      | find_13      | 2       |
      | findIndex_14 | 1       |
      | some_15      | Yes     |
      | every_16     | Yes     |
      | at_17        | a       |
      | at_18        | 1       |
      | at_19        | b       |
      | at_20        |         |
      | at_21        | c       |
      | at_22        | c       |
      | at_23        |         |
      | first_24     | a       |
      | first_25     | b       |
      | first_26     |         |
      | last_27      | c       |
      | last_28      | a       |
      | last_29      |         |
      | slice_30     | b, c    |
    Then the formula properties show these values for row 2
      | name         | value   |
      | at_1         | 2       |
      | first_2      | 1       |
      | last_3       | 3       |
      | slice_4      | 2, 3    |
      | concat_5     | 1, 2, 3 |
      | sort_6       | 1, 2, 3 |
      | reverse_7    | 3, 2, 1 |
      | unique_8     | 1, 2    |
      | includes_9   | Yes     |
      | flat_10      | 1, 2, 3 |
      | map_11       | 2, 4, 6 |
      | filter_12    | 2, 3    |
      | find_13      | 2       |
      | findIndex_14 | 1       |
      | some_15      | Yes     |
      | every_16     | Yes     |
      | at_17        | b       |
      | at_18        | 1       |
      | at_19        | b       |
      | at_20        |         |
      | at_21        |         |
      | at_22        | b       |
      | at_23        |         |
      | first_24     | b       |
      | first_25     | b       |
      | first_26     |         |
      | last_27      | b       |
      | last_28      | a       |
      | last_29      |         |
      | slice_30     |         |
    Then the formula properties show these values for row 3
      | name         | value   |
      | at_1         | 2       |
      | first_2      | 1       |
      | last_3       | 3       |
      | slice_4      | 2, 3    |
      | concat_5     | 1, 2, 3 |
      | sort_6       | 1, 2, 3 |
      | reverse_7    | 3, 2, 1 |
      | unique_8     | 1, 2    |
      | includes_9   | Yes     |
      | flat_10      | 1, 2, 3 |
      | map_11       | 2, 4, 6 |
      | filter_12    | 2, 3    |
      | find_13      | 2       |
      | findIndex_14 | 1       |
      | some_15      | Yes     |
      | every_16     | Yes     |
      | at_17        |         |
      | at_18        | 1       |
      | at_19        | b       |
      | at_20        |         |
      | at_21        |         |
      | at_22        |         |
      | at_23        |         |
      | first_24     |         |
      | first_25     | b       |
      | first_26     |         |
      | last_27      |         |
      | last_28      | a       |
      | last_29      |         |
      | slice_30     |         |

  Scenario: List cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                                     |
      | slice_31    | slice([1, 2, 3], 1)                            |
      | slice_32    | slice(["b", "a", "c", "a"], 1)                 |
      | slice_33    | slice([], 1)                                   |
      | slice_34    | slice(prop("Tags"), 0)                         |
      | slice_35    | slice(prop("Tags"), 1, 2)                      |
      | slice_36    | slice(prop("Tags"), 1, 10)                     |
      | concat_37   | concat(prop("Num"))                            |
      | concat_38   | concat(prop("Name"))                           |
      | concat_39   | concat(prop("Note"))                           |
      | concat_40   | concat(prop("Flag"))                           |
      | concat_41   | concat(prop("Tags"))                           |
      | concat_42   | concat([1, 2, 3])                              |
      | concat_43   | concat(prop("Num"), prop("Name"))              |
      | concat_44   | concat(prop("Num"), prop("Neg"), prop("Zero")) |
      | concat_45   | concat(prop("Num"), prop("Zero"))              |
      | sort_46     | sort(prop("Tags"))                             |
      | sort_47     | sort([1, 2, 3])                                |
      | sort_48     | sort(["b", "a", "c", "a"])                     |
      | sort_49     | sort([])                                       |
      | reverse_50  | reverse(prop("Tags"))                          |
      | reverse_51  | reverse(["b", "a", "c", "a"])                  |
      | reverse_52  | reverse([])                                    |
      | unique_53   | unique(prop("Tags"))                           |
      | unique_54   | unique([1, 2, 3])                              |
      | unique_55   | unique(["b", "a", "c", "a"])                   |
      | unique_56   | unique([])                                     |
      | includes_57 | includes(prop("Tags"), prop("Num"))            |
      | includes_58 | includes([1, 2, 3], prop("Num"))               |
      | includes_59 | includes(["b", "a", "c", "a"], prop("Num"))    |
      | includes_60 | includes([], prop("Num"))                      |
    Then the formula properties show these values for row 1
      | name        | value           |
      | slice_31    | 2, 3            |
      | slice_32    | a, c, a         |
      | slice_33    |                 |
      | slice_34    | a, b, c         |
      | slice_35    | b               |
      | slice_36    | b, c            |
      | concat_37   | 8               |
      | concat_38   | Ada Lovelace    |
      | concat_39   | Hello, World!   |
      | concat_40   | Yes             |
      | concat_41   | a, b, c         |
      | concat_42   | 1, 2, 3         |
      | concat_43   | 8, Ada Lovelace |
      | concat_44   | 8, -2.5, 0      |
      | concat_45   | 8, 0            |
      | sort_46     | a, b, c         |
      | sort_47     | 1, 2, 3         |
      | sort_48     | a, a, b, c      |
      | sort_49     |                 |
      | reverse_50  | c, b, a         |
      | reverse_51  | a, c, a, b      |
      | reverse_52  |                 |
      | unique_53   | a, b, c         |
      | unique_54   | 1, 2, 3         |
      | unique_55   | b, a, c         |
      | unique_56   |                 |
      | includes_57 | No              |
      | includes_58 | No              |
      | includes_59 | No              |
      | includes_60 | No              |
    Then the formula properties show these values for row 2
      | name        | value        |
      | slice_31    | 2, 3         |
      | slice_32    | a, c, a      |
      | slice_33    |              |
      | slice_34    | b            |
      | slice_35    |              |
      | slice_36    |              |
      | concat_37   | 3.75         |
      | concat_38   | notion       |
      | concat_39   | x            |
      | concat_40   | No           |
      | concat_41   | b            |
      | concat_42   | 1, 2, 3      |
      | concat_43   | 3.75, notion |
      | concat_44   | 3.75, 1.5, 7 |
      | concat_45   | 3.75, 7      |
      | sort_46     | b            |
      | sort_47     | 1, 2, 3      |
      | sort_48     | a, a, b, c   |
      | sort_49     |              |
      | reverse_50  | b            |
      | reverse_51  | a, c, a, b   |
      | reverse_52  |              |
      | unique_53   | b            |
      | unique_54   | 1, 2, 3      |
      | unique_55   | b, a, c      |
      | unique_56   |              |
      | includes_57 | No           |
      | includes_58 | No           |
      | includes_59 | No           |
      | includes_60 | No           |
    Then the formula properties show these values for row 3
      | name        | value      |
      | slice_31    | 2, 3       |
      | slice_32    | a, c, a    |
      | slice_33    |            |
      | slice_34    |            |
      | slice_35    |            |
      | slice_36    |            |
      | concat_37   |            |
      | concat_38   | Row3       |
      | concat_39   |            |
      | concat_40   | No         |
      | concat_41   |            |
      | concat_42   | 1, 2, 3    |
      | concat_43   | Row3       |
      | concat_44   |            |
      | concat_45   |            |
      | sort_46     |            |
      | sort_47     | 1, 2, 3    |
      | sort_48     | a, a, b, c |
      | sort_49     |            |
      | reverse_50  |            |
      | reverse_51  | a, c, a, b |
      | reverse_52  |            |
      | unique_53   |            |
      | unique_54   | 1, 2, 3    |
      | unique_55   | b, a, c    |
      | unique_56   |            |
      | includes_57 | No         |
      | includes_58 | No         |
      | includes_59 | No         |
      | includes_60 | No         |

  Scenario: List cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name        | expression                                                 |
      | includes_61 | includes(prop("Tags"), prop("Name"))                       |
      | includes_62 | includes(prop("Tags"), prop("Note"))                       |
      | includes_63 | includes(prop("Tags"), prop("Flag"))                       |
      | includes_64 | includes(prop("Tags"), prop("Tags"))                       |
      | includes_65 | includes(prop("Tags"), [1, 2, 3])                          |
      | flat_66     | flat(prop("Tags"))                                         |
      | flat_67     | flat([1, 2, 3])                                            |
      | flat_68     | flat(["b", "a", "c", "a"])                                 |
      | flat_69     | flat([])                                                   |
      | prop_70     | prop("Tags").map(current + "!")                            |
      | prop_71     | prop("Tags").map(format(index) + ":" + current)            |
      | operator_72 | [1, 2, 3].map(current * prop("Num"))                       |
      | prop_73     | prop("Tags").filter(current != "b")                        |
      | operator_74 | [1, 2, 3, 4].filter(current % 2 == 0)                      |
      | operator_75 | [1, 2, 3].filter(current > 10)                             |
      | prop_76     | prop("Tags").find(current == "b")                          |
      | prop_77     | prop("Tags").find(current == "z")                          |
      | operator_78 | [5, 6, 7].findIndex(current == 7)                          |
      | operator_79 | [5, 6, 7].findIndex(current == 0)                          |
      | prop_80     | prop("Tags").some(current == "c")                          |
      | prop_81     | prop("Tags").some(current == "z")                          |
      | operator_82 | [].some(true)                                              |
      | prop_83     | prop("Tags").every(length(current) == 1)                   |
      | operator_84 | [].every(false)                                            |
      | prop_85     | prop("Tags").map(upper(current)).join("-")                 |
      | prop_86     | prop("Tags").filter(current != "a").map(current + current) |
      | prop_87     | prop("Tags").sort().reverse()                              |
      | operator_88 | [3, 1, 2].sort()                                           |
      | operator_89 | ["b", "a", "c"].sort()                                     |
      | operator_90 | [3, 1, 2].sort().first()                                   |
    Then the formula properties show these values for row 1
      | name        | value         |
      | includes_61 | No            |
      | includes_62 | No            |
      | includes_63 | No            |
      | includes_64 | No            |
      | includes_65 | No            |
      | flat_66     | a, b, c       |
      | flat_67     | 1, 2, 3       |
      | flat_68     | b, a, c, a    |
      | flat_69     |               |
      | prop_70     | a!, b!, c!    |
      | prop_71     | 0:a, 1:b, 2:c |
      | operator_72 | 8, 16, 24     |
      | prop_73     | a, c          |
      | operator_74 | 2, 4          |
      | operator_75 |               |
      | prop_76     | b             |
      | prop_77     |               |
      | operator_78 | 2             |
      | operator_79 | -1            |
      | prop_80     | Yes           |
      | prop_81     | No            |
      | operator_82 | No            |
      | prop_83     | Yes           |
      | operator_84 | Yes           |
      | prop_85     | A-B-C         |
      | prop_86     | bb, cc        |
      | prop_87     | c, b, a       |
      | operator_88 | 1, 2, 3       |
      | operator_89 | a, b, c       |
      | operator_90 | 1             |
    Then the formula properties show these values for row 2
      | name        | value            |
      | includes_61 | No               |
      | includes_62 | No               |
      | includes_63 | No               |
      | includes_64 | No               |
      | includes_65 | No               |
      | flat_66     | b                |
      | flat_67     | 1, 2, 3          |
      | flat_68     | b, a, c, a       |
      | flat_69     |                  |
      | prop_70     | b!               |
      | prop_71     | 0:b              |
      | operator_72 | 3.75, 7.5, 11.25 |
      | prop_73     |                  |
      | operator_74 | 2, 4             |
      | operator_75 |                  |
      | prop_76     | b                |
      | prop_77     |                  |
      | operator_78 | 2                |
      | operator_79 | -1               |
      | prop_80     | No               |
      | prop_81     | No               |
      | operator_82 | No               |
      | prop_83     | Yes              |
      | operator_84 | Yes              |
      | prop_85     | B                |
      | prop_86     | bb               |
      | prop_87     | b                |
      | operator_88 | 1, 2, 3          |
      | operator_89 | a, b, c          |
      | operator_90 | 1                |
    Then the formula properties show these values for row 3
      | name        | value      |
      | includes_61 | No         |
      | includes_62 | No         |
      | includes_63 | No         |
      | includes_64 | No         |
      | includes_65 | No         |
      | flat_66     |            |
      | flat_67     | 1, 2, 3    |
      | flat_68     | b, a, c, a |
      | flat_69     |            |
      | prop_70     |            |
      | prop_71     |            |
      | operator_72 | 0, 0, 0    |
      | prop_73     |            |
      | operator_74 | 2, 4       |
      | operator_75 |            |
      | prop_76     |            |
      | prop_77     |            |
      | operator_78 | 2          |
      | operator_79 | -1         |
      | prop_80     | No         |
      | prop_81     | No         |
      | operator_82 | No         |
      | prop_83     | Yes        |
      | operator_84 | Yes        |
      | prop_85     |            |
      | prop_86     |            |
      | prop_87     |            |
      | operator_88 | 1, 2, 3    |
      | operator_89 | a, b, c    |
      | operator_90 | 1          |

  Scenario: List cases 4
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression                                                      |
      | operator_91  | [3, 1, 2].sort().last()                                         |
      | operator_92  | [1, 2, 2, 3, 1].unique()                                        |
      | operator_93  | [[1, 2], [3]].flat()                                            |
      | operator_94  | [1, 2].concat([3], [4, 5])                                      |
      | prop_95      | prop("Tags").concat(["z"])                                      |
      | prop_96      | prop("Tags").includes("b")                                      |
      | prop_97      | prop("Tags").includes("z")                                      |
      | operator_98  | [1, 2, 3].includes(prop("Num"))                                 |
      | prop_99      | prop("Tags").at(1)                                              |
      | prop_100     | prop("Tags").at(5)                                              |
      | prop_101     | prop("Tags").slice(1)                                           |
      | prop_102     | prop("Tags").slice(0, 2)                                        |
      | prop_103     | prop("Tags").reverse().join("")                                 |
      | split_104    | split(prop("Name"), " ").length()                               |
      | split_105    | split(prop("Name"), " ").first()                                |
      | split_106    | split(prop("Name"), " ").map(substring(current, 0, 1)).join("") |
      | split_107    | split("a,b,,c", ",")                                            |
      | split_108    | split("abc", "")                                                |
      | operator_109 | [1, 2, 3].join(", ")                                            |
      | join_110     | join(prop("Tags"), " + ")                                       |
      | sum_111      | sum(prop("Tags").map(length(current)))                          |
      | mean_112     | mean([1, 2, 3, 4])                                              |
      | median_113   | median([3, 1, 2])                                               |
      | median_114   | median([4, 1, 2, 3])                                            |
      | max_115      | max([1, 9, 3])                                                  |
      | min_116      | min([1, 9, 3])                                                  |
      | operator_117 | [1, 2] == [1, 2]                                                |
      | operator_118 | [1, 2] == [2, 1]                                                |
      | prop_119     | prop("Tags") + ["d"]                                            |
      | operator_120 | ["x"] + ["y"]                                                   |
    Then the formula properties show these values for row 1
      | name         | value         |
      | operator_91  | 3             |
      | operator_92  | 1, 2, 3       |
      | operator_93  | 1, 2, 3       |
      | operator_94  | 1, 2, 3, 4, 5 |
      | prop_95      | a, b, c, z    |
      | prop_96      | Yes           |
      | prop_97      | No            |
      | operator_98  | No            |
      | prop_99      | b             |
      | prop_100     |               |
      | prop_101     | b, c          |
      | prop_102     | a, b          |
      | prop_103     | cba           |
      | split_104    | 2             |
      | split_105    | Ada           |
      | split_106    | AL            |
      | split_107    | a, b, , c     |
      | split_108    | a, b, c       |
      | operator_109 | 1, 2, 3       |
      | join_110     | a + b + c     |
      | sum_111      | 3             |
      | mean_112     | 2.5           |
      | median_113   | 2             |
      | median_114   | 2.5           |
      | max_115      | 9             |
      | min_116      | 1             |
      | operator_117 | Yes           |
      | operator_118 | No            |
      | prop_119     | a, b, cd      |
      | operator_120 | xy            |
    Then the formula properties show these values for row 2
      | name         | value         |
      | operator_91  | 3             |
      | operator_92  | 1, 2, 3       |
      | operator_93  | 1, 2, 3       |
      | operator_94  | 1, 2, 3, 4, 5 |
      | prop_95      | b, z          |
      | prop_96      | Yes           |
      | prop_97      | No            |
      | operator_98  | No            |
      | prop_99      |               |
      | prop_100     |               |
      | prop_101     |               |
      | prop_102     | b             |
      | prop_103     | b             |
      | split_104    | 1             |
      | split_105    | notion        |
      | split_106    | n             |
      | split_107    | a, b, , c     |
      | split_108    | a, b, c       |
      | operator_109 | 1, 2, 3       |
      | join_110     | b             |
      | sum_111      | 1             |
      | mean_112     | 2.5           |
      | median_113   | 2             |
      | median_114   | 2.5           |
      | max_115      | 9             |
      | min_116      | 1             |
      | operator_117 | Yes           |
      | operator_118 | No            |
      | prop_119     | bd            |
      | operator_120 | xy            |
    Then the formula properties show these values for row 3
      | name         | value         |
      | operator_91  | 3             |
      | operator_92  | 1, 2, 3       |
      | operator_93  | 1, 2, 3       |
      | operator_94  | 1, 2, 3, 4, 5 |
      | prop_95      | z             |
      | prop_96      | No            |
      | prop_97      | No            |
      | operator_98  | No            |
      | prop_99      |               |
      | prop_100     |               |
      | prop_101     |               |
      | prop_102     |               |
      | prop_103     |               |
      | split_104    | 1             |
      | split_105    | Row3          |
      | split_106    | R             |
      | split_107    | a, b, , c     |
      | split_108    | a, b, c       |
      | operator_109 | 1, 2, 3       |
      | join_110     |               |
      | sum_111      | 0             |
      | mean_112     | 2.5           |
      | median_113   | 2             |
      | median_114   | 2.5           |
      | max_115      | 9             |
      | min_116      | 1             |
      | operator_117 | Yes           |
      | operator_118 | No            |
      | prop_119     | d             |
      | operator_120 | xy            |

  Scenario: List cases 5
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression      |
      | operator_121 | [1, 2, 3] + [4] |
    Then the formula properties show these values for row 1
      | name         | value    |
      | operator_121 | 1, 2, 34 |
    Then the formula properties show these values for row 2
      | name         | value    |
      | operator_121 | 1, 2, 34 |
    Then the formula properties show these values for row 3
      | name         | value    |
      | operator_121 | 1, 2, 34 |

  Scenario: List type errors
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I start a new formula property
    Then these formulas show these errors
      | expression                | error                                                    |
      | [1, "a", true].join("\|") | List items must have the same type: number vs text [1,5] |
