@formula @formula-matrix @formula-matrix-date
Feature: Formula matrix: Date
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Date cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name             | expression                                         |
      | timestamp_1      | timestamp(parseDate("1970-01-02"))                 |
      | fromTimestamp_2  | fromTimestamp(0)                                   |
      | day_3            | day(parseDate("2024-01-01"))                       |
      | date_4           | date(parseDate("2024-01-15"))                      |
      | week_5           | week(parseDate("2024-01-01"))                      |
      | month_6          | month(parseDate("2024-03-01"))                     |
      | year_7           | year(parseDate("2024-03-01"))                      |
      | dateAdd_8        | dateAdd(prop("When"), 2, "weeks")                  |
      | dateRange_9      | dateRange(prop("When"), prop("When"))              |
      | dateStart_10     | dateStart(prop("When"))                            |
      | dateEnd_11       | dateEnd(prop("When"))                              |
      | parseDate_12     | parseDate("2024-03-01")                            |
      | formatDate_13    | formatDate(parseDate("2024-03-01"), "MMM D, YYYY") |
      | timestamp_14     | timestamp(prop("When"))                            |
      | timestamp_15     | timestamp(parseDate("2024-02-29"))                 |
      | timestamp_16     | timestamp(fromTimestamp(1700000000000))            |
      | fromTimestamp_17 | fromTimestamp(1709294400000)                       |
      | fromTimestamp_18 | fromTimestamp(prop("Num"))                         |
      | fromTimestamp_19 | fromTimestamp(prop("Zero"))                        |
      | minute_20        | minute(prop("When"))                               |
      | minute_21        | minute(parseDate("2024-02-29"))                    |
      | minute_22        | minute(fromTimestamp(1700000000000))               |
      | hour_23          | hour(prop("When"))                                 |
      | hour_24          | hour(parseDate("2024-02-29"))                      |
      | hour_25          | hour(fromTimestamp(1700000000000))                 |
      | day_26           | day(prop("When"))                                  |
      | day_27           | day(parseDate("2024-02-29"))                       |
      | day_28           | day(fromTimestamp(1700000000000))                  |
      | date_29          | date(prop("When"))                                 |
      | date_30          | date(parseDate("2024-02-29"))                      |
    Then the formula properties show these values for row 1
      | name             | value                   |
      | timestamp_1      | 86400000                |
      | fromTimestamp_2  | 01/01/1970 12:00 AM     |
      | day_3            | 1                       |
      | date_4           | 15                      |
      | week_5           | 1                       |
      | month_6          | 3                       |
      | year_7           | 2024                    |
      | dateAdd_8        | 03/19/2024              |
      | dateRange_9      | 03/05/2024 → 03/05/2024 |
      | dateStart_10     | 03/05/2024              |
      | dateEnd_11       | 03/05/2024              |
      | parseDate_12     | 03/01/2024              |
      | formatDate_13    | Mar 1, 2024             |
      | timestamp_14     | 1709596800000           |
      | timestamp_15     | 1709164800000           |
      | timestamp_16     | 1700000000000           |
      | fromTimestamp_17 | 03/01/2024 12:00 PM     |
      | fromTimestamp_18 | 01/01/1970 12:00 AM     |
      | fromTimestamp_19 | 01/01/1970 12:00 AM     |
      | minute_20        | 0                       |
      | minute_21        | 0                       |
      | minute_22        | 13                      |
      | hour_23          | 0                       |
      | hour_24          | 0                       |
      | hour_25          | 22                      |
      | day_26           | 2                       |
      | day_27           | 4                       |
      | day_28           | 2                       |
      | date_29          | 5                       |
      | date_30          | 29                      |
    Then the formula properties show these values for row 2
      | name             | value                   |
      | timestamp_1      | 86400000                |
      | fromTimestamp_2  | 01/01/1970 12:00 AM     |
      | day_3            | 1                       |
      | date_4           | 15                      |
      | week_5           | 1                       |
      | month_6          | 3                       |
      | year_7           | 2024                    |
      | dateAdd_8        | 01/14/2025              |
      | dateRange_9      | 12/31/2024 → 12/31/2024 |
      | dateStart_10     | 12/31/2024              |
      | dateEnd_11       | 12/31/2024              |
      | parseDate_12     | 03/01/2024              |
      | formatDate_13    | Mar 1, 2024             |
      | timestamp_14     | 1735603200000           |
      | timestamp_15     | 1709164800000           |
      | timestamp_16     | 1700000000000           |
      | fromTimestamp_17 | 03/01/2024 12:00 PM     |
      | fromTimestamp_18 | 01/01/1970 12:00 AM     |
      | fromTimestamp_19 | 01/01/1970 12:00 AM     |
      | minute_20        | 0                       |
      | minute_21        | 0                       |
      | minute_22        | 13                      |
      | hour_23          | 0                       |
      | hour_24          | 0                       |
      | hour_25          | 22                      |
      | day_26           | 2                       |
      | day_27           | 4                       |
      | day_28           | 2                       |
      | date_29          | 31                      |
      | date_30          | 29                      |
    Then the formula properties show these values for row 3
      | name             | value               |
      | timestamp_1      | 86400000            |
      | fromTimestamp_2  | 01/01/1970 12:00 AM |
      | day_3            | 1                   |
      | date_4           | 15                  |
      | week_5           | 1                   |
      | month_6          | 3                   |
      | year_7           | 2024                |
      | dateAdd_8        |                     |
      | dateRange_9      |                     |
      | dateStart_10     |                     |
      | dateEnd_11       |                     |
      | parseDate_12     | 03/01/2024          |
      | formatDate_13    | Mar 1, 2024         |
      | timestamp_14     |                     |
      | timestamp_15     | 1709164800000       |
      | timestamp_16     | 1700000000000       |
      | fromTimestamp_17 | 03/01/2024 12:00 PM |
      | fromTimestamp_18 |                     |
      | fromTimestamp_19 |                     |
      | minute_20        |                     |
      | minute_21        | 0                   |
      | minute_22        | 13                  |
      | hour_23          |                     |
      | hour_24          | 0                   |
      | hour_25          | 22                  |
      | day_26           |                     |
      | day_27           | 4                   |
      | day_28           | 2                   |
      | date_29          |                     |
      | date_30          | 29                  |

  Scenario: Date cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name            | expression                                                      |
      | date_31         | date(fromTimestamp(1700000000000))                              |
      | week_32         | week(prop("When"))                                              |
      | week_33         | week(parseDate("2024-02-29"))                                   |
      | week_34         | week(fromTimestamp(1700000000000))                              |
      | month_35        | month(prop("When"))                                             |
      | month_36        | month(parseDate("2024-02-29"))                                  |
      | month_37        | month(fromTimestamp(1700000000000))                             |
      | year_38         | year(prop("When"))                                              |
      | year_39         | year(parseDate("2024-02-29"))                                   |
      | year_40         | year(fromTimestamp(1700000000000))                              |
      | dateAdd_41      | dateAdd(prop("When"), prop("Num"), "days")                      |
      | dateAdd_42      | dateAdd(parseDate("2024-02-29"), prop("Num"), "days")           |
      | dateAdd_43      | dateAdd(fromTimestamp(1700000000000), prop("Num"), "days")      |
      | dateAdd_44      | dateAdd(prop("When"), prop("Neg"), "days")                      |
      | dateAdd_45      | dateAdd(prop("When"), prop("Zero"), "days")                     |
      | dateAdd_46      | dateAdd(prop("When"), 2, "days")                                |
      | dateAdd_47      | dateAdd(prop("When"), 0, "days")                                |
      | dateAdd_48      | dateAdd(prop("When"), -1.5, "days")                             |
      | dateAdd_49      | dateAdd(prop("When"), prop("Num"), "months")                    |
      | dateAdd_50      | dateAdd(prop("When"), prop("Num"), "years")                     |
      | dateAdd_51      | dateAdd(prop("When"), prop("Num"), "hours")                     |
      | dateAdd_52      | dateAdd(prop("When"), prop("Num"), "minutes")                   |
      | dateAdd_53      | dateAdd(prop("When"), prop("Num"), "weeks")                     |
      | dateAdd_54      | dateAdd(prop("When"), prop("Num"), "quarters")                  |
      | dateSubtract_55 | dateSubtract(prop("When"), prop("Num"), "days")                 |
      | dateSubtract_56 | dateSubtract(parseDate("2024-02-29"), prop("Num"), "days")      |
      | dateSubtract_57 | dateSubtract(fromTimestamp(1700000000000), prop("Num"), "days") |
      | dateSubtract_58 | dateSubtract(prop("When"), prop("Neg"), "days")                 |
      | dateSubtract_59 | dateSubtract(prop("When"), prop("Zero"), "days")                |
      | dateSubtract_60 | dateSubtract(prop("When"), 2, "days")                           |
    Then the formula properties show these values for row 1
      | name            | value               |
      | date_31         | 14                  |
      | week_32         | 10                  |
      | week_33         | 9                   |
      | week_34         | 46                  |
      | month_35        | 3                   |
      | month_36        | 2                   |
      | month_37        | 11                  |
      | year_38         | 2024                |
      | year_39         | 2024                |
      | year_40         | 2023                |
      | dateAdd_41      | 03/13/2024          |
      | dateAdd_42      | 03/08/2024          |
      | dateAdd_43      | 11/22/2023 10:13 PM |
      | dateAdd_44      | 03/03/2024          |
      | dateAdd_45      | 03/05/2024          |
      | dateAdd_46      | 03/07/2024          |
      | dateAdd_47      | 03/05/2024          |
      | dateAdd_48      | 03/04/2024          |
      | dateAdd_49      | 11/05/2024          |
      | dateAdd_50      | 03/05/2032          |
      | dateAdd_51      | 03/05/2024          |
      | dateAdd_52      | 03/05/2024          |
      | dateAdd_53      | 04/30/2024          |
      | dateAdd_54      | 03/05/2026          |
      | dateSubtract_55 | 02/26/2024          |
      | dateSubtract_56 | 02/21/2024          |
      | dateSubtract_57 | 11/06/2023 10:13 PM |
      | dateSubtract_58 | 03/08/2024          |
      | dateSubtract_59 | 03/05/2024          |
      | dateSubtract_60 | 03/03/2024          |
    Then the formula properties show these values for row 2
      | name            | value               |
      | date_31         | 14                  |
      | week_32         | 1                   |
      | week_33         | 9                   |
      | week_34         | 46                  |
      | month_35        | 12                  |
      | month_36        | 2                   |
      | month_37        | 11                  |
      | year_38         | 2024                |
      | year_39         | 2024                |
      | year_40         | 2023                |
      | dateAdd_41      | 01/04/2025          |
      | dateAdd_42      | 03/04/2024          |
      | dateAdd_43      | 11/18/2023 10:13 PM |
      | dateAdd_44      | 01/02/2025          |
      | dateAdd_45      | 01/07/2025          |
      | dateAdd_46      | 01/02/2025          |
      | dateAdd_47      | 12/31/2024          |
      | dateAdd_48      | 12/30/2024          |
      | dateAdd_49      | 03/31/2025          |
      | dateAdd_50      | 12/31/2027          |
      | dateAdd_51      | 12/31/2024          |
      | dateAdd_52      | 12/31/2024          |
      | dateAdd_53      | 01/26/2025          |
      | dateAdd_54      | 11/30/2025          |
      | dateSubtract_55 | 12/27/2024          |
      | dateSubtract_56 | 02/25/2024          |
      | dateSubtract_57 | 11/10/2023 10:13 PM |
      | dateSubtract_58 | 12/30/2024          |
      | dateSubtract_59 | 12/24/2024          |
      | dateSubtract_60 | 12/29/2024          |
    Then the formula properties show these values for row 3
      | name            | value               |
      | date_31         | 14                  |
      | week_32         |                     |
      | week_33         | 9                   |
      | week_34         | 46                  |
      | month_35        |                     |
      | month_36        | 2                   |
      | month_37        | 11                  |
      | year_38         |                     |
      | year_39         | 2024                |
      | year_40         | 2023                |
      | dateAdd_41      |                     |
      | dateAdd_42      | 02/29/2024          |
      | dateAdd_43      | 11/14/2023 10:13 PM |
      | dateAdd_44      |                     |
      | dateAdd_45      |                     |
      | dateAdd_46      |                     |
      | dateAdd_47      |                     |
      | dateAdd_48      |                     |
      | dateAdd_49      |                     |
      | dateAdd_50      |                     |
      | dateAdd_51      |                     |
      | dateAdd_52      |                     |
      | dateAdd_53      |                     |
      | dateAdd_54      |                     |
      | dateSubtract_55 |                     |
      | dateSubtract_56 | 02/29/2024          |
      | dateSubtract_57 | 11/14/2023 10:13 PM |
      | dateSubtract_58 |                     |
      | dateSubtract_59 |                     |
      | dateSubtract_60 |                     |

  Scenario: Date cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name            | expression                                                      |
      | dateSubtract_61 | dateSubtract(prop("When"), 0, "days")                           |
      | dateSubtract_62 | dateSubtract(prop("When"), -1.5, "days")                        |
      | dateSubtract_63 | dateSubtract(prop("When"), prop("Num"), "months")               |
      | dateSubtract_64 | dateSubtract(prop("When"), prop("Num"), "years")                |
      | dateSubtract_65 | dateSubtract(prop("When"), prop("Num"), "hours")                |
      | dateSubtract_66 | dateSubtract(prop("When"), prop("Num"), "weeks")                |
      | dateBetween_67  | dateBetween(prop("When"), prop("When"), "days")                 |
      | dateBetween_68  | dateBetween(parseDate("2024-02-29"), prop("When"), "days")      |
      | dateBetween_69  | dateBetween(fromTimestamp(1700000000000), prop("When"), "days") |
      | dateBetween_70  | dateBetween(prop("When"), parseDate("2024-02-29"), "days")      |
      | dateBetween_71  | dateBetween(prop("When"), fromTimestamp(1700000000000), "days") |
      | dateBetween_72  | dateBetween(prop("When"), prop("When"), "hours")                |
      | dateBetween_73  | dateBetween(prop("When"), prop("When"), "minutes")              |
      | dateBetween_74  | dateBetween(prop("When"), prop("When"), "weeks")                |
      | dateBetween_75  | dateBetween(prop("When"), prop("When"), "months")               |
      | dateBetween_76  | dateBetween(prop("When"), prop("When"), "years")                |
      | dateBetween_77  | dateBetween(prop("When"), prop("When"), "quarters")             |
      | dateRange_78    | dateRange(parseDate("2024-02-29"), prop("When"))                |
      | dateRange_79    | dateRange(fromTimestamp(1700000000000), prop("When"))           |
      | dateRange_80    | dateRange(prop("When"), parseDate("2024-02-29"))                |
      | dateRange_81    | dateRange(prop("When"), fromTimestamp(1700000000000))           |
      | dateStart_82    | dateStart(parseDate("2024-02-29"))                              |
      | dateStart_83    | dateStart(fromTimestamp(1700000000000))                         |
      | dateEnd_84      | dateEnd(parseDate("2024-02-29"))                                |
      | dateEnd_85      | dateEnd(fromTimestamp(1700000000000))                           |
      | parseDate_86    | parseDate("2024-03-05")                                         |
      | parseDate_87    | parseDate("2024-03-05T10:30:00")                                |
      | parseDate_88    | parseDate("March 5, 2024")                                      |
      | parseDate_89    | parseDate("not a date")                                         |
      | parseDate_90    | parseDate(prop("Note"))                                         |
    Then the formula properties show these values for row 1
      | name            | value                                     |
      | dateSubtract_61 | 03/05/2024                                |
      | dateSubtract_62 | 03/07/2024                                |
      | dateSubtract_63 | 07/05/2023                                |
      | dateSubtract_64 | 03/05/2016                                |
      | dateSubtract_65 | 03/04/2024                                |
      | dateSubtract_66 | 01/09/2024                                |
      | dateBetween_67  | 0                                         |
      | dateBetween_68  | -5                                        |
      | dateBetween_69  | -111                                      |
      | dateBetween_70  | 5                                         |
      | dateBetween_71  | 111                                       |
      | dateBetween_72  | 0                                         |
      | dateBetween_73  | 0                                         |
      | dateBetween_74  | 0                                         |
      | dateBetween_75  | 0                                         |
      | dateBetween_76  | 0                                         |
      | dateBetween_77  | 0                                         |
      | dateRange_78    | 02/29/2024 → 03/05/2024                   |
      | dateRange_79    | 11/14/2023 10:13 PM → 03/05/2024 12:00 AM |
      | dateRange_80    | 03/05/2024 → 02/29/2024                   |
      | dateRange_81    | 03/05/2024 12:00 AM → 11/14/2023 10:13 PM |
      | dateStart_82    | 02/29/2024                                |
      | dateStart_83    | 11/14/2023 10:13 PM                       |
      | dateEnd_84      | 02/29/2024                                |
      | dateEnd_85      | 11/14/2023 10:13 PM                       |
      | parseDate_86    | 03/05/2024                                |
      | parseDate_87    | 03/05/2024 10:30 AM                       |
      | parseDate_88    | 03/05/2024                                |
      | parseDate_89    |                                           |
      | parseDate_90    |                                           |
    Then the formula properties show these values for row 2
      | name            | value                                     |
      | dateSubtract_61 | 12/31/2024                                |
      | dateSubtract_62 | 01/02/2025                                |
      | dateSubtract_63 | 08/31/2024                                |
      | dateSubtract_64 | 12/31/2020                                |
      | dateSubtract_65 | 12/30/2024                                |
      | dateSubtract_66 | 12/05/2024                                |
      | dateBetween_67  | 0                                         |
      | dateBetween_68  | -306                                      |
      | dateBetween_69  | -412                                      |
      | dateBetween_70  | 306                                       |
      | dateBetween_71  | 412                                       |
      | dateBetween_72  | 0                                         |
      | dateBetween_73  | 0                                         |
      | dateBetween_74  | 0                                         |
      | dateBetween_75  | 0                                         |
      | dateBetween_76  | 0                                         |
      | dateBetween_77  | 0                                         |
      | dateRange_78    | 02/29/2024 → 12/31/2024                   |
      | dateRange_79    | 11/14/2023 10:13 PM → 12/31/2024 12:00 AM |
      | dateRange_80    | 12/31/2024 → 02/29/2024                   |
      | dateRange_81    | 12/31/2024 12:00 AM → 11/14/2023 10:13 PM |
      | dateStart_82    | 02/29/2024                                |
      | dateStart_83    | 11/14/2023 10:13 PM                       |
      | dateEnd_84      | 02/29/2024                                |
      | dateEnd_85      | 11/14/2023 10:13 PM                       |
      | parseDate_86    | 03/05/2024                                |
      | parseDate_87    | 03/05/2024 10:30 AM                       |
      | parseDate_88    | 03/05/2024                                |
      | parseDate_89    |                                           |
      | parseDate_90    |                                           |
    Then the formula properties show these values for row 3
      | name            | value               |
      | dateSubtract_61 |                     |
      | dateSubtract_62 |                     |
      | dateSubtract_63 |                     |
      | dateSubtract_64 |                     |
      | dateSubtract_65 |                     |
      | dateSubtract_66 |                     |
      | dateBetween_67  |                     |
      | dateBetween_68  |                     |
      | dateBetween_69  |                     |
      | dateBetween_70  |                     |
      | dateBetween_71  |                     |
      | dateBetween_72  |                     |
      | dateBetween_73  |                     |
      | dateBetween_74  |                     |
      | dateBetween_75  |                     |
      | dateBetween_76  |                     |
      | dateBetween_77  |                     |
      | dateRange_78    | 02/29/2024          |
      | dateRange_79    | 11/14/2023 10:13 PM |
      | dateRange_80    |                     |
      | dateRange_81    |                     |
      | dateStart_82    | 02/29/2024          |
      | dateStart_83    | 11/14/2023 10:13 PM |
      | dateEnd_84      | 02/29/2024          |
      | dateEnd_85      | 11/14/2023 10:13 PM |
      | parseDate_86    | 03/05/2024          |
      | parseDate_87    | 03/05/2024 10:30 AM |
      | parseDate_88    | 03/05/2024          |
      | parseDate_89    |                     |
      | parseDate_90    |                     |

  Scenario: Date cases 4
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name          | expression                                             |
      | parseDate_91  | parseDate(prop("Name"))                                |
      | formatDate_92 | formatDate(prop("When"), "YYYY-MM-DD")                 |
      | formatDate_93 | formatDate(parseDate("2024-02-29"), "YYYY-MM-DD")      |
      | formatDate_94 | formatDate(fromTimestamp(1700000000000), "YYYY-MM-DD") |
      | formatDate_95 | formatDate(prop("When"), "MMM D, YYYY")                |
      | formatDate_96 | formatDate(prop("When"), "dddd")                       |
      | formatDate_97 | formatDate(prop("When"), "HH:mm")                      |
      | formatDate_98 | formatDate(prop("When"), "[Q]Q YYYY")                  |
      | formatDate_99 | formatDate(prop("When"), "YYYY-MM-DD HH:mm:ss")        |
    Then the formula properties show these values for row 1
      | name          | value               |
      | parseDate_91  |                     |
      | formatDate_92 | 2024-03-05          |
      | formatDate_93 | 2024-02-29          |
      | formatDate_94 | 2023-11-14          |
      | formatDate_95 | Mar 5, 2024         |
      | formatDate_96 | Tuesday             |
      | formatDate_97 | 00:00               |
      | formatDate_98 | Q1 2024             |
      | formatDate_99 | 2024-03-05 00:00:00 |
    Then the formula properties show these values for row 2
      | name          | value               |
      | parseDate_91  |                     |
      | formatDate_92 | 2024-12-31          |
      | formatDate_93 | 2024-02-29          |
      | formatDate_94 | 2023-11-14          |
      | formatDate_95 | Dec 31, 2024        |
      | formatDate_96 | Tuesday             |
      | formatDate_97 | 00:00               |
      | formatDate_98 | Q4 2024             |
      | formatDate_99 | 2024-12-31 00:00:00 |
    Then the formula properties show these values for row 3
      | name          | value      |
      | parseDate_91  |            |
      | formatDate_92 |            |
      | formatDate_93 | 2024-02-29 |
      | formatDate_94 | 2023-11-14 |
      | formatDate_95 |            |
      | formatDate_96 |            |
      | formatDate_97 |            |
      | formatDate_98 |            |
      | formatDate_99 |            |
