@formula @formula-matrix @formula-matrix-chains
Feature: Formula matrix: Chains
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Chains cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name            | expression                                                                                                                     |
      | chain_total     | prop("Num") + prop("Neg")                                                                                                      |
      | chain_double    | prop("chain_total") * 2                                                                                                        |
      | chain_label     | prop("Name") + ": " + format(prop("chain_double"))                                                                             |
      | chain_flag      | prop("chain_double") > 10                                                                                                      |
      | chain_pick      | if(prop("chain_flag"), upper(prop("chain_label")), lower(prop("chain_label")))                                                 |
      | chain_date      | dateAdd(prop("When"), prop("Num"), "days")                                                                                     |
      | chain_date_text | formatDate(prop("chain_date"), "YYYY-MM-DD")                                                                                   |
      | chain_days      | dateBetween(prop("chain_date"), prop("When"), "days")                                                                          |
      | chain_list      | prop("Tags").map(current + format(prop("chain_total")))                                                                        |
      | chain_list_len  | length(prop("chain_list")) + prop("chain_days")                                                                                |
      | chain_empty     | empty(prop("chain_total")) ? "no total" : format(prop("chain_total"))                                                          |
      | chain_deep      | prop("chain_pick") + "/" + prop("chain_date_text") + "/" + prop("chain_list").join("+") + "/" + format(prop("chain_list_len")) |
    Then the formula properties show these values for row 1
      | name            | value                                         |
      | chain_total     | 5.5                                           |
      | chain_double    | 11                                            |
      | chain_label     | Ada Lovelace: 11                              |
      | chain_flag      | Yes                                           |
      | chain_pick      | ADA LOVELACE: 11                              |
      | chain_date      | 03/13/2024                                    |
      | chain_date_text | 2024-03-13                                    |
      | chain_days      | 8                                             |
      | chain_list      | a5.5, b5.5, c5.5                              |
      | chain_list_len  | 11                                            |
      | chain_empty     | 5.5                                           |
      | chain_deep      | ADA LOVELACE: 11/2024-03-13/a5.5+b5.5+c5.5/11 |
    Then the formula properties show these values for row 2
      | name            | value                           |
      | chain_total     | 5.25                            |
      | chain_double    | 10.5                            |
      | chain_label     | notion: 10.5                    |
      | chain_flag      | Yes                             |
      | chain_pick      | NOTION: 10.5                    |
      | chain_date      | 01/04/2025                      |
      | chain_date_text | 2025-01-04                      |
      | chain_days      | 4                               |
      | chain_list      | b5.25                           |
      | chain_list_len  | 5                               |
      | chain_empty     | 5.25                            |
      | chain_deep      | NOTION: 10.5/2025-01-04/b5.25/5 |
    Then the formula properties show these values for row 3
      | name            | value       |
      | chain_total     |             |
      | chain_double    | 0           |
      | chain_label     | Row3: 0     |
      | chain_flag      | No          |
      | chain_pick      | row3: 0     |
      | chain_date      |             |
      | chain_date_text |             |
      | chain_days      |             |
      | chain_list      |             |
      | chain_list_len  | 0           |
      | chain_empty     | no total    |
      | chain_deep      | row3: 0///0 |
