@formula @formula-matrix @formula-matrix-text
Feature: Formula matrix: Text
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Text cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name          | expression                   |
      | length_1      | length("hello")              |
      | length_2      | [1, 2, 3].length()           |
      | substring_3   | substring("Notion", 0, 3)    |
      | substring_4   | substring("Notion", 3)       |
      | contains_5    | contains("Notion", "ot")     |
      | test_6        | test("Notion", "Not")        |
      | test_7        | test("Notion", "\\\\d")      |
      | match_8       | match("a1b22", "\\\\d+")     |
      | replace_9     | replace("a-b-c", "-", "+")   |
      | replaceAll_10 | replaceAll("a-b-c", "-", "") |
      | lower_11      | lower("HELLO")               |
      | upper_12      | upper("hello")               |
      | repeat_13     | repeat("*", 3)               |
      | trim_14       | trim("  hi  ")               |
      | split_15      | split("a,b,c", ",")          |
      | join_16       | join(["a", "b"], ", ")       |
      | format_17     | format(42)                   |
      | format_18     | format(true)                 |
      | toNumber_19   | toNumber("42")               |
      | toNumber_20   | toNumber(true)               |
      | length_21     | length(prop("Name"))         |
      | length_22     | length(prop("Note"))         |
      | length_23     | length("abc")                |
      | length_24     | length("")                   |
      | length_25     | length(prop("Tag"))          |
      | length_26     | length(prop("Tags"))         |
      | length_27     | length([1, 2, 3])            |
      | length_28     | length(["b", "a", "c", "a"]) |
      | length_29     | length([])                   |
      | substring_30  | substring(prop("Name"), 0)   |
    Then the formula properties show these values for row 1
      | name          | value        |
      | length_1      | 5            |
      | length_2      | 3            |
      | substring_3   | Not          |
      | substring_4   | ion          |
      | contains_5    | Yes          |
      | test_6        | Yes          |
      | test_7        | No           |
      | match_8       | 1, 22        |
      | replace_9     | a+b-c        |
      | replaceAll_10 | abc          |
      | lower_11      | hello        |
      | upper_12      | HELLO        |
      | repeat_13     | ***          |
      | trim_14       | hi           |
      | split_15      | a, b, c      |
      | join_16       | a, b         |
      | format_17     | 42           |
      | format_18     | true         |
      | toNumber_19   | 42           |
      | toNumber_20   | 1            |
      | length_21     | 12           |
      | length_22     | 13           |
      | length_23     | 3            |
      | length_24     | 0            |
      | length_25     | 5            |
      | length_26     | 3            |
      | length_27     | 3            |
      | length_28     | 4            |
      | length_29     | 0            |
      | substring_30  | Ada Lovelace |
    Then the formula properties show these values for row 2
      | name          | value   |
      | length_1      | 5       |
      | length_2      | 3       |
      | substring_3   | Not     |
      | substring_4   | ion     |
      | contains_5    | Yes     |
      | test_6        | Yes     |
      | test_7        | No      |
      | match_8       | 1, 22   |
      | replace_9     | a+b-c   |
      | replaceAll_10 | abc     |
      | lower_11      | hello   |
      | upper_12      | HELLO   |
      | repeat_13     | ***     |
      | trim_14       | hi      |
      | split_15      | a, b, c |
      | join_16       | a, b    |
      | format_17     | 42      |
      | format_18     | true    |
      | toNumber_19   | 42      |
      | toNumber_20   | 1       |
      | length_21     | 6       |
      | length_22     | 1       |
      | length_23     | 3       |
      | length_24     | 0       |
      | length_25     | 4       |
      | length_26     | 1       |
      | length_27     | 3       |
      | length_28     | 4       |
      | length_29     | 0       |
      | substring_30  | notion  |
    Then the formula properties show these values for row 3
      | name          | value   |
      | length_1      | 5       |
      | length_2      | 3       |
      | substring_3   | Not     |
      | substring_4   | ion     |
      | contains_5    | Yes     |
      | test_6        | Yes     |
      | test_7        | No      |
      | match_8       | 1, 22   |
      | replace_9     | a+b-c   |
      | replaceAll_10 | abc     |
      | lower_11      | hello   |
      | upper_12      | HELLO   |
      | repeat_13     | ***     |
      | trim_14       | hi      |
      | split_15      | a, b, c |
      | join_16       | a, b    |
      | format_17     | 42      |
      | format_18     | true    |
      | toNumber_19   | 42      |
      | toNumber_20   | 1       |
      | length_21     | 4       |
      | length_22     | 0       |
      | length_23     | 3       |
      | length_24     | 0       |
      | length_25     | 0       |
      | length_26     | 0       |
      | length_27     | 3       |
      | length_28     | 4       |
      | length_29     | 0       |
      | substring_30  | Row3    |

  Scenario: Text cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression                           |
      | substring_31 | substring(prop("Note"), 0)           |
      | substring_32 | substring("abc", 0)                  |
      | substring_33 | substring("", 0)                     |
      | substring_34 | substring(prop("Tag"), 0)            |
      | substring_35 | substring(prop("Name"), 2)           |
      | substring_36 | substring(prop("Name"), 10)          |
      | substring_37 | substring(prop("Name"), 0, 3)        |
      | substring_38 | substring(prop("Name"), 0, 100)      |
      | contains_39  | contains(prop("Name"), prop("Name")) |
      | contains_40  | contains(prop("Note"), prop("Name")) |
      | contains_41  | contains("abc", prop("Name"))        |
      | contains_42  | contains("", prop("Name"))           |
      | contains_43  | contains(prop("Tag"), prop("Name"))  |
      | contains_44  | contains(prop("Name"), prop("Note")) |
      | contains_45  | contains(prop("Name"), "abc")        |
      | contains_46  | contains(prop("Name"), "")           |
      | contains_47  | contains(prop("Name"), prop("Tag"))  |
      | test_48      | test(prop("Name"), "^[A-Z]")         |
      | test_49      | test(prop("Note"), "^[A-Z]")         |
      | test_50      | test("abc", "^[A-Z]")                |
      | test_51      | test("", "^[A-Z]")                   |
      | test_52      | test(prop("Tag"), "^[A-Z]")          |
      | test_53      | test(prop("Name"), "\\\\d+")         |
      | test_54      | test(prop("Name"), "o.i")            |
      | match_55     | match(prop("Name"), "[a-z]+")        |
      | match_56     | match(prop("Note"), "[a-z]+")        |
      | match_57     | match("abc", "[a-z]+")               |
      | match_58     | match("", "[a-z]+")                  |
      | match_59     | match(prop("Tag"), "[a-z]+")         |
      | match_60     | match(prop("Name"), "\\\\d")         |
    Then the formula properties show these values for row 1
      | name         | value         |
      | substring_31 | Hello, World! |
      | substring_32 | abc           |
      | substring_33 |               |
      | substring_34 | alpha         |
      | substring_35 | a Lovelace    |
      | substring_36 | ce            |
      | substring_37 | Ada           |
      | substring_38 | Ada Lovelace  |
      | contains_39  | Yes           |
      | contains_40  | No            |
      | contains_41  | No            |
      | contains_42  | No            |
      | contains_43  | No            |
      | contains_44  | No            |
      | contains_45  | No            |
      | contains_46  | Yes           |
      | contains_47  | No            |
      | test_48      | Yes           |
      | test_49      | Yes           |
      | test_50      | No            |
      | test_51      | No            |
      | test_52      | No            |
      | test_53      | No            |
      | test_54      | No            |
      | match_55     | da, ovelace   |
      | match_56     | ello, orld    |
      | match_57     | abc           |
      | match_58     |               |
      | match_59     | alpha         |
      | match_60     |               |
    Then the formula properties show these values for row 2
      | name         | value  |
      | substring_31 | x      |
      | substring_32 | abc    |
      | substring_33 |        |
      | substring_34 | beta   |
      | substring_35 | tion   |
      | substring_36 |        |
      | substring_37 | not    |
      | substring_38 | notion |
      | contains_39  | Yes    |
      | contains_40  | No     |
      | contains_41  | No     |
      | contains_42  | No     |
      | contains_43  | No     |
      | contains_44  | No     |
      | contains_45  | No     |
      | contains_46  | Yes    |
      | contains_47  | No     |
      | test_48      | No     |
      | test_49      | No     |
      | test_50      | No     |
      | test_51      | No     |
      | test_52      | No     |
      | test_53      | No     |
      | test_54      | Yes    |
      | match_55     | notion |
      | match_56     | x      |
      | match_57     | abc    |
      | match_58     |        |
      | match_59     | beta   |
      | match_60     |        |
    Then the formula properties show these values for row 3
      | name         | value |
      | substring_31 |       |
      | substring_32 | abc   |
      | substring_33 |       |
      | substring_34 |       |
      | substring_35 | w3    |
      | substring_36 |       |
      | substring_37 | Row   |
      | substring_38 | Row3  |
      | contains_39  | Yes   |
      | contains_40  | No    |
      | contains_41  | No    |
      | contains_42  | No    |
      | contains_43  | No    |
      | contains_44  | Yes   |
      | contains_45  | No    |
      | contains_46  | Yes   |
      | contains_47  | Yes   |
      | test_48      | Yes   |
      | test_49      | No    |
      | test_50      | No    |
      | test_51      | No    |
      | test_52      | No    |
      | test_53      | Yes   |
      | test_54      | No    |
      | match_55     | ow    |
      | match_56     |       |
      | match_57     | abc   |
      | match_58     |       |
      | match_59     |       |
      | match_60     | 3     |

  Scenario: Text cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name          | expression                               |
      | match_61      | match(prop("Name"), "o")                 |
      | replace_62    | replace(prop("Name"), "o", "0")          |
      | replace_63    | replace(prop("Note"), "o", "0")          |
      | replace_64    | replace("abc", "o", "0")                 |
      | replace_65    | replace("", "o", "0")                    |
      | replace_66    | replace(prop("Tag"), "o", "0")           |
      | replace_67    | replace(prop("Name"), "[aeiou]", "0")    |
      | replace_68    | replace(prop("Name"), "^.", "0")         |
      | replace_69    | replace(prop("Name"), "o", "-")          |
      | replaceAll_70 | replaceAll(prop("Name"), "o", "0")       |
      | replaceAll_71 | replaceAll(prop("Note"), "o", "0")       |
      | replaceAll_72 | replaceAll("abc", "o", "0")              |
      | replaceAll_73 | replaceAll("", "o", "0")                 |
      | replaceAll_74 | replaceAll(prop("Tag"), "o", "0")        |
      | replaceAll_75 | replaceAll(prop("Name"), "[aeiou]", "0") |
      | replaceAll_76 | replaceAll(prop("Name"), "l+", "0")      |
      | replaceAll_77 | replaceAll(prop("Name"), "o", "-")       |
      | lower_78      | lower(prop("Name"))                      |
      | lower_79      | lower(prop("Note"))                      |
      | lower_80      | lower("abc")                             |
      | lower_81      | lower("")                                |
      | lower_82      | lower(prop("Tag"))                       |
      | upper_83      | upper(prop("Name"))                      |
      | upper_84      | upper(prop("Note"))                      |
      | upper_85      | upper("abc")                             |
      | upper_86      | upper("")                                |
      | upper_87      | upper(prop("Tag"))                       |
      | repeat_88     | repeat(prop("Name"), 3)                  |
      | repeat_89     | repeat(prop("Note"), 3)                  |
      | repeat_90     | repeat("abc", 3)                         |
    Then the formula properties show these values for row 1
      | name          | value                                   |
      | match_61      | o                                       |
      | replace_62    | Ada L0velace                            |
      | replace_63    | Hell0, World!                           |
      | replace_64    | abc                                     |
      | replace_65    |                                         |
      | replace_66    | alpha                                   |
      | replace_67    | Ad0 Lovelace                            |
      | replace_68    | 0da Lovelace                            |
      | replace_69    | Ada L-velace                            |
      | replaceAll_70 | Ada L0velace                            |
      | replaceAll_71 | Hell0, W0rld!                           |
      | replaceAll_72 | abc                                     |
      | replaceAll_73 |                                         |
      | replaceAll_74 | alpha                                   |
      | replaceAll_75 | Ad0 L0v0l0c0                            |
      | replaceAll_76 | Ada Love0ace                            |
      | replaceAll_77 | Ada L-velace                            |
      | lower_78      | ada lovelace                            |
      | lower_79      | hello, world!                           |
      | lower_80      | abc                                     |
      | lower_81      |                                         |
      | lower_82      | alpha                                   |
      | upper_83      | ADA LOVELACE                            |
      | upper_84      | HELLO, WORLD!                           |
      | upper_85      | ABC                                     |
      | upper_86      |                                         |
      | upper_87      | ALPHA                                   |
      | repeat_88     | Ada LovelaceAda LovelaceAda Lovelace    |
      | repeat_89     | Hello, World!Hello, World!Hello, World! |
      | repeat_90     | abcabcabc                               |
    Then the formula properties show these values for row 2
      | name          | value              |
      | match_61      | o, o               |
      | replace_62    | n0tion             |
      | replace_63    | x                  |
      | replace_64    | abc                |
      | replace_65    |                    |
      | replace_66    | beta               |
      | replace_67    | n0tion             |
      | replace_68    | 0otion             |
      | replace_69    | n-tion             |
      | replaceAll_70 | n0ti0n             |
      | replaceAll_71 | x                  |
      | replaceAll_72 | abc                |
      | replaceAll_73 |                    |
      | replaceAll_74 | beta               |
      | replaceAll_75 | n0t00n             |
      | replaceAll_76 | notion             |
      | replaceAll_77 | n-ti-n             |
      | lower_78      | notion             |
      | lower_79      | x                  |
      | lower_80      | abc                |
      | lower_81      |                    |
      | lower_82      | beta               |
      | upper_83      | NOTION             |
      | upper_84      | X                  |
      | upper_85      | ABC                |
      | upper_86      |                    |
      | upper_87      | BETA               |
      | repeat_88     | notionnotionnotion |
      | repeat_89     | xxx                |
      | repeat_90     | abcabcabc          |
    Then the formula properties show these values for row 3
      | name          | value        |
      | match_61      | o            |
      | replace_62    | R0w3         |
      | replace_63    |              |
      | replace_64    | abc          |
      | replace_65    |              |
      | replace_66    |              |
      | replace_67    | R0w3         |
      | replace_68    | 0ow3         |
      | replace_69    | R-w3         |
      | replaceAll_70 | R0w3         |
      | replaceAll_71 |              |
      | replaceAll_72 | abc          |
      | replaceAll_73 |              |
      | replaceAll_74 |              |
      | replaceAll_75 | R0w3         |
      | replaceAll_76 | Row3         |
      | replaceAll_77 | R-w3         |
      | lower_78      | row3         |
      | lower_79      |              |
      | lower_80      | abc          |
      | lower_81      |              |
      | lower_82      |              |
      | upper_83      | ROW3         |
      | upper_84      |              |
      | upper_85      | ABC          |
      | upper_86      |              |
      | upper_87      |              |
      | repeat_88     | Row3Row3Row3 |
      | repeat_89     |              |
      | repeat_90     | abcabcabc    |

  Scenario: Text cases 4
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression                         |
      | repeat_91    | repeat("", 3)                      |
      | repeat_92    | repeat(prop("Tag"), 3)             |
      | repeat_93    | repeat(prop("Name"), 0)            |
      | repeat_94    | repeat(prop("Name"), prop("Zero")) |
      | trim_95      | trim(prop("Name"))                 |
      | trim_96      | trim(prop("Note"))                 |
      | trim_97      | trim("abc")                        |
      | trim_98      | trim("")                           |
      | trim_99      | trim(prop("Tag"))                  |
      | split_100    | split(prop("Name"), ",")           |
      | split_101    | split(prop("Note"), ",")           |
      | split_102    | split("abc", ",")                  |
      | split_103    | split("", ",")                     |
      | split_104    | split(prop("Tag"), ",")            |
      | split_105    | split(prop("Name"), " ")           |
      | split_106    | split(prop("Name"), "")            |
      | split_107    | split(prop("Name"), "o")           |
      | join_108     | join(prop("Tags"), ", ")           |
      | join_109     | join([1, 2, 3], ", ")              |
      | join_110     | join(["b", "a", "c", "a"], ", ")   |
      | join_111     | join([], ", ")                     |
      | join_112     | join(prop("Tags"), "-")            |
      | join_113     | join(prop("Tags"), "")             |
      | format_114   | format(prop("Num"))                |
      | format_115   | format(prop("Name"))               |
      | format_116   | format(prop("Note"))               |
      | format_117   | format(prop("Flag"))               |
      | format_118   | format(prop("Tags"))               |
      | format_119   | format([1, 2, 3])                  |
      | toNumber_120 | toNumber(prop("Num"))              |
    Then the formula properties show these values for row 1
      | name         | value                              |
      | repeat_91    |                                    |
      | repeat_92    | alphaalphaalpha                    |
      | repeat_93    |                                    |
      | repeat_94    |                                    |
      | trim_95      | Ada Lovelace                       |
      | trim_96      | Hello, World!                      |
      | trim_97      | abc                                |
      | trim_98      |                                    |
      | trim_99      | alpha                              |
      | split_100    | Ada Lovelace                       |
      | split_101    | Hello,  World!                     |
      | split_102    | abc                                |
      | split_103    |                                    |
      | split_104    | alpha                              |
      | split_105    | Ada, Lovelace                      |
      | split_106    | A, d, a,  , L, o, v, e, l, a, c, e |
      | split_107    | Ada L, velace                      |
      | join_108     | a, b, c                            |
      | join_109     | 1, 2, 3                            |
      | join_110     | b, a, c, a                         |
      | join_111     |                                    |
      | join_112     | a-b-c                              |
      | join_113     | abc                                |
      | format_114   | 8                                  |
      | format_115   | Ada Lovelace                       |
      | format_116   | Hello, World!                      |
      | format_117   | true                               |
      | format_118   | a, b, c                            |
      | format_119   | 1, 2, 3                            |
      | toNumber_120 | 8                                  |
    Then the formula properties show these values for row 2
      | name         | value                                      |
      | repeat_91    |                                            |
      | repeat_92    | betabetabeta                               |
      | repeat_93    |                                            |
      | repeat_94    | notionnotionnotionnotionnotionnotionnotion |
      | trim_95      | notion                                     |
      | trim_96      | x                                          |
      | trim_97      | abc                                        |
      | trim_98      |                                            |
      | trim_99      | beta                                       |
      | split_100    | notion                                     |
      | split_101    | x                                          |
      | split_102    | abc                                        |
      | split_103    |                                            |
      | split_104    | beta                                       |
      | split_105    | notion                                     |
      | split_106    | n, o, t, i, o, n                           |
      | split_107    | n, ti, n                                   |
      | join_108     | b                                          |
      | join_109     | 1, 2, 3                                    |
      | join_110     | b, a, c, a                                 |
      | join_111     |                                            |
      | join_112     | b                                          |
      | join_113     | b                                          |
      | format_114   | 3.75                                       |
      | format_115   | notion                                     |
      | format_116   | x                                          |
      | format_117   | false                                      |
      | format_118   | b                                          |
      | format_119   | 1, 2, 3                                    |
      | toNumber_120 | 3.75                                       |
    Then the formula properties show these values for row 3
      | name         | value      |
      | repeat_91    |            |
      | repeat_92    |            |
      | repeat_93    |            |
      | repeat_94    |            |
      | trim_95      | Row3       |
      | trim_96      |            |
      | trim_97      | abc        |
      | trim_98      |            |
      | trim_99      |            |
      | split_100    | Row3       |
      | split_101    |            |
      | split_102    | abc        |
      | split_103    |            |
      | split_104    |            |
      | split_105    | Row3       |
      | split_106    | R, o, w, 3 |
      | split_107    | R, w3      |
      | join_108     |            |
      | join_109     | 1, 2, 3    |
      | join_110     | b, a, c, a |
      | join_111     |            |
      | join_112     |            |
      | join_113     |            |
      | format_114   |            |
      | format_115   | Row3       |
      | format_116   |            |
      | format_117   | false      |
      | format_118   |            |
      | format_119   | 1, 2, 3    |
      | toNumber_120 |            |

  Scenario: Text cases 5
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name         | expression             |
      | toNumber_121 | toNumber(prop("Name")) |
      | toNumber_122 | toNumber(prop("Note")) |
      | toNumber_123 | toNumber(prop("Flag")) |
      | toNumber_124 | toNumber(prop("Tags")) |
      | toNumber_125 | toNumber([1, 2, 3])    |
    Then the formula properties show these values for row 1
      | name         | value |
      | toNumber_121 |       |
      | toNumber_122 |       |
      | toNumber_123 | 1     |
      | toNumber_124 |       |
      | toNumber_125 |       |
    Then the formula properties show these values for row 2
      | name         | value |
      | toNumber_121 |       |
      | toNumber_122 |       |
      | toNumber_123 | 0     |
      | toNumber_124 |       |
      | toNumber_125 |       |
    Then the formula properties show these values for row 3
      | name         | value |
      | toNumber_121 |       |
      | toNumber_122 |       |
      | toNumber_123 | 0     |
      | toNumber_124 |       |
      | toNumber_125 |       |
