@formula @formula-matrix @formula-matrix-empty
Feature: Formula matrix: Empty
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Empty cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name           | expression                                                 |
      | prop_1         | prop("Num") + 1                                            |
      | prop_2         | prop("Num") * 2                                            |
      | prop_3         | prop("Zero") * 2                                           |
      | format_4       | format(prop("Zero"))                                       |
      | format_5       | format(prop("When"))                                       |
      | format_6       | format(prop("Tag"))                                        |
      | format_7       | format(empty())                                            |
      | prop_8         | prop("Note") + "!"                                         |
      | prop_9         | prop("Tags").join(", ")                                    |
      | prop_10        | prop("Tags").first()                                       |
      | prop_11        | prop("Tags").last()                                        |
      | prop_12        | prop("Tags").length()                                      |
      | prop_13        | prop("Tag") + "?"                                          |
      | prop_14        | prop("Tag") == "alpha"                                     |
      | if_15          | if(empty(prop("Zero")), "empty", "has value")              |
      | empty_16       | empty(prop("Zero")) ? 0 : prop("Zero") * 10                |
      | dateAdd_17     | dateAdd(prop("When"), 1, "days")                           |
      | dateBetween_18 | dateBetween(prop("When"), parseDate("2024-01-01"), "days") |
      | toNumber_19    | toNumber(prop("Tag"))                                      |
      | toNumber_20    | toNumber("")                                               |
      | toNumber_21    | toNumber("12.5abc")                                        |
      | toNumber_22    | toNumber("abc")                                            |
      | toNumber_23    | toNumber(prop("When"))                                     |
      | prop_24        | prop("Flag") + 0                                           |
      | prop_25        | prop("Num") + prop("Flag")                                 |
    Then the formula properties show these values for row 1
      | name           | value          |
      | prop_1         | 9              |
      | prop_2         | 16             |
      | prop_3         | 0              |
      | format_4       | 0              |
      | format_5       | Mar 5, 2024    |
      | format_6       | alpha          |
      | format_7       |                |
      | prop_8         | Hello, World!! |
      | prop_9         | a, b, c        |
      | prop_10        | a              |
      | prop_11        | c              |
      | prop_12        | 3              |
      | prop_13        | alpha?         |
      | prop_14        | Yes            |
      | if_15          | empty          |
      | empty_16       | 0              |
      | dateAdd_17     | 03/06/2024     |
      | dateBetween_18 | 64             |
      | toNumber_19    |                |
      | toNumber_20    |                |
      | toNumber_21    |                |
      | toNumber_22    |                |
      | toNumber_23    | 1709596800000  |
      | prop_24        | true0          |
      | prop_25        | 8true          |
    Then the formula properties show these values for row 2
      | name           | value         |
      | prop_1         | 4.75          |
      | prop_2         | 7.5           |
      | prop_3         | 14            |
      | format_4       | 7             |
      | format_5       | Dec 31, 2024  |
      | format_6       | beta          |
      | format_7       |               |
      | prop_8         | x!            |
      | prop_9         | b             |
      | prop_10        | b             |
      | prop_11        | b             |
      | prop_12        | 1             |
      | prop_13        | beta?         |
      | prop_14        | No            |
      | if_15          | has value     |
      | empty_16       | 70            |
      | dateAdd_17     | 01/01/2025    |
      | dateBetween_18 | 365           |
      | toNumber_19    |               |
      | toNumber_20    |               |
      | toNumber_21    |               |
      | toNumber_22    |               |
      | toNumber_23    | 1735603200000 |
      | prop_24        | false0        |
      | prop_25        | 3.75false     |
    Then the formula properties show these values for row 3
      | name           | value  |
      | prop_1         | 1      |
      | prop_2         | 0      |
      | prop_3         | 0      |
      | format_4       |        |
      | format_5       |        |
      | format_6       |        |
      | format_7       |        |
      | prop_8         | !      |
      | prop_9         |        |
      | prop_10        |        |
      | prop_11        |        |
      | prop_12        | 0      |
      | prop_13        | ?      |
      | prop_14        | No     |
      | if_15          | empty  |
      | empty_16       | 0      |
      | dateAdd_17     |        |
      | dateBetween_18 |        |
      | toNumber_19    |        |
      | toNumber_20    |        |
      | toNumber_21    |        |
      | toNumber_22    |        |
      | toNumber_23    |        |
      | prop_24        | false0 |
      | prop_25        | false  |
