@formula @formula-matrix @formula-matrix-logic
Feature: Formula matrix: Logic
  Generated by src/application/database-yjs/fields/formula/__tests__/
  formula-matrix.generate.test.ts from the
  function catalogue: every documented example, every parameter with a
  matching property, a literal, an empty property and a wrong type, plus
  operators, empty semantics and nested combinations. Cell texts are
  asserted exactly on the fixed fixture. Date and time texts assume the
  UTC timezone the generator ran in.

  Scenario: Logic cases 1
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name       | expression                                         |
      | if_1       | if(true, 1, 2)                                     |
      | if_2       | if(prop("Flag") == true, "Complete", "Incomplete") |
      | ifs_3      | ifs(true, 1, true, 2, 3)                           |
      | ifs_4      | ifs(false, 1, false, 2, 3)                         |
      | ifs_5      | ifs(false, "Overdue")                              |
      | empty_6    | empty(0)                                           |
      | empty_7    | empty([])                                          |
      | empty_8    | if(empty(prop("When")), empty(), prop("When"))     |
      | equal_9    | equal(1, 1)                                        |
      | equal_10   | "a" == "b"                                         |
      | unequal_11 | unequal(1, 2)                                      |
      | and_12     | and(true, false)                                   |
      | and_13     | prop("Flag") and prop("Flag")                      |
      | or_14      | or(true, false)                                    |
      | not_15     | not(true)                                          |
      | let_16     | let(x, 2, x * x)                                   |
      | let_17     | let(tax, prop("Num") * 0.1, prop("Num") + tax)     |
      | lets_18    | lets(a, 1, b, 2, a + b)                            |
      | and_19     | true and false                                     |
      | or_20      | true or false                                      |
      | not_21     | not true                                           |
      | empty_22   | empty(prop("Num"))                                 |
      | empty_23   | empty(prop("Name"))                                |
      | empty_24   | empty(prop("Note"))                                |
      | empty_25   | empty(prop("Flag"))                                |
      | empty_26   | empty(prop("Tags"))                                |
      | empty_27   | empty([1, 2, 3])                                   |
      | equal_28   | equal(prop("Num"), prop("Num"))                    |
      | equal_29   | equal(prop("Name"), prop("Num"))                   |
      | equal_30   | equal(prop("Note"), prop("Num"))                   |
    Then the formula properties show these values for row 1
      | name       | value      |
      | if_1       | 1          |
      | if_2       | Complete   |
      | ifs_3      | 1          |
      | ifs_4      | 3          |
      | ifs_5      |            |
      | empty_6    | Yes        |
      | empty_7    | Yes        |
      | empty_8    | 03/05/2024 |
      | equal_9    | Yes        |
      | equal_10   | No         |
      | unequal_11 | Yes        |
      | and_12     | No         |
      | and_13     | Yes        |
      | or_14      | Yes        |
      | not_15     | No         |
      | let_16     | 4          |
      | let_17     | 8.8        |
      | lets_18    | 3          |
      | and_19     | No         |
      | or_20      | Yes        |
      | not_21     | No         |
      | empty_22   | No         |
      | empty_23   | No         |
      | empty_24   | No         |
      | empty_25   | No         |
      | empty_26   | No         |
      | empty_27   | No         |
      | equal_28   | Yes        |
      | equal_29   | No         |
      | equal_30   | No         |
    Then the formula properties show these values for row 2
      | name       | value      |
      | if_1       | 1          |
      | if_2       | Incomplete |
      | ifs_3      | 1          |
      | ifs_4      | 3          |
      | ifs_5      |            |
      | empty_6    | Yes        |
      | empty_7    | Yes        |
      | empty_8    | 12/31/2024 |
      | equal_9    | Yes        |
      | equal_10   | No         |
      | unequal_11 | Yes        |
      | and_12     | No         |
      | and_13     | No         |
      | or_14      | Yes        |
      | not_15     | No         |
      | let_16     | 4          |
      | let_17     | 4.125      |
      | lets_18    | 3          |
      | and_19     | No         |
      | or_20      | Yes        |
      | not_21     | No         |
      | empty_22   | No         |
      | empty_23   | No         |
      | empty_24   | No         |
      | empty_25   | Yes        |
      | empty_26   | No         |
      | empty_27   | No         |
      | equal_28   | Yes        |
      | equal_29   | No         |
      | equal_30   | No         |
    Then the formula properties show these values for row 3
      | name       | value      |
      | if_1       | 1          |
      | if_2       | Incomplete |
      | ifs_3      | 1          |
      | ifs_4      | 3          |
      | ifs_5      |            |
      | empty_6    | Yes        |
      | empty_7    | Yes        |
      | empty_8    |            |
      | equal_9    | Yes        |
      | equal_10   | No         |
      | unequal_11 | Yes        |
      | and_12     | No         |
      | and_13     | No         |
      | or_14      | Yes        |
      | not_15     | No         |
      | let_16     | 4          |
      | let_17     | 0          |
      | lets_18    | 3          |
      | and_19     | No         |
      | or_20      | Yes        |
      | not_21     | No         |
      | empty_22   | Yes        |
      | empty_23   | No         |
      | empty_24   | Yes        |
      | empty_25   | Yes        |
      | empty_26   | Yes        |
      | empty_27   | No         |
      | equal_28   | Yes        |
      | equal_29   | No         |
      | equal_30   | Yes        |

  Scenario: Logic cases 2
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name       | expression                                                   |
      | equal_31   | equal(prop("Flag"), prop("Num"))                             |
      | equal_32   | equal(prop("Tags"), prop("Num"))                             |
      | equal_33   | equal([1, 2, 3], prop("Num"))                                |
      | equal_34   | equal(prop("Num"), prop("Name"))                             |
      | equal_35   | equal(prop("Num"), prop("Note"))                             |
      | equal_36   | equal(prop("Num"), prop("Flag"))                             |
      | equal_37   | equal(prop("Num"), prop("Tags"))                             |
      | equal_38   | equal(prop("Num"), [1, 2, 3])                                |
      | unequal_39 | unequal(prop("Num"), prop("Num"))                            |
      | unequal_40 | unequal(prop("Name"), prop("Num"))                           |
      | unequal_41 | unequal(prop("Note"), prop("Num"))                           |
      | unequal_42 | unequal(prop("Flag"), prop("Num"))                           |
      | unequal_43 | unequal(prop("Tags"), prop("Num"))                           |
      | unequal_44 | unequal([1, 2, 3], prop("Num"))                              |
      | unequal_45 | unequal(prop("Num"), prop("Name"))                           |
      | unequal_46 | unequal(prop("Num"), prop("Note"))                           |
      | unequal_47 | unequal(prop("Num"), prop("Flag"))                           |
      | unequal_48 | unequal(prop("Num"), prop("Tags"))                           |
      | unequal_49 | unequal(prop("Num"), [1, 2, 3])                              |
      | not_50     | not(prop("Flag"))                                            |
      | not_51     | not(false)                                                   |
      | if_52      | if(prop("Flag"), "yes", "no")                                |
      | if_53      | if(prop("Num") > 5, prop("Num") * 2, prop("Num") / 2)        |
      | if_54      | if(empty(prop("Note")), "none", prop("Note"))                |
      | ifs_55     | ifs(prop("Num") > 5, "big", prop("Num") > 2, "mid", "small") |
      | ifs_56     | ifs(prop("Flag"), "flag", prop("Zero") > 0, "zero", "none")  |
      | ifs_57     | ifs(false, "a", false, "b")                                  |
      | and_58     | and(prop("Flag"), prop("Num") > 5)                           |
      | or_59      | or(prop("Flag"), prop("Zero") > 5)                           |
      | not_60     | not(empty(prop("Num")))                                      |
    Then the formula properties show these values for row 1
      | name       | value         |
      | equal_31   | No            |
      | equal_32   | No            |
      | equal_33   | No            |
      | equal_34   | No            |
      | equal_35   | No            |
      | equal_36   | No            |
      | equal_37   | No            |
      | equal_38   | No            |
      | unequal_39 | No            |
      | unequal_40 | Yes           |
      | unequal_41 | Yes           |
      | unequal_42 | Yes           |
      | unequal_43 | Yes           |
      | unequal_44 | Yes           |
      | unequal_45 | Yes           |
      | unequal_46 | Yes           |
      | unequal_47 | Yes           |
      | unequal_48 | Yes           |
      | unequal_49 | Yes           |
      | not_50     | No            |
      | not_51     | Yes           |
      | if_52      | yes           |
      | if_53      | 16            |
      | if_54      | Hello, World! |
      | ifs_55     | big           |
      | ifs_56     | flag          |
      | ifs_57     |               |
      | and_58     | Yes           |
      | or_59      | Yes           |
      | not_60     | Yes           |
    Then the formula properties show these values for row 2
      | name       | value |
      | equal_31   | No    |
      | equal_32   | No    |
      | equal_33   | No    |
      | equal_34   | No    |
      | equal_35   | No    |
      | equal_36   | No    |
      | equal_37   | No    |
      | equal_38   | No    |
      | unequal_39 | No    |
      | unequal_40 | Yes   |
      | unequal_41 | Yes   |
      | unequal_42 | Yes   |
      | unequal_43 | Yes   |
      | unequal_44 | Yes   |
      | unequal_45 | Yes   |
      | unequal_46 | Yes   |
      | unequal_47 | Yes   |
      | unequal_48 | Yes   |
      | unequal_49 | Yes   |
      | not_50     | Yes   |
      | not_51     | Yes   |
      | if_52      | no    |
      | if_53      | 1.875 |
      | if_54      | x     |
      | ifs_55     | mid   |
      | ifs_56     | zero  |
      | ifs_57     |       |
      | and_58     | No    |
      | or_59      | Yes   |
      | not_60     | Yes   |
    Then the formula properties show these values for row 3
      | name       | value |
      | equal_31   | Yes   |
      | equal_32   | Yes   |
      | equal_33   | No    |
      | equal_34   | No    |
      | equal_35   | Yes   |
      | equal_36   | Yes   |
      | equal_37   | Yes   |
      | equal_38   | No    |
      | unequal_39 | No    |
      | unequal_40 | Yes   |
      | unequal_41 | No    |
      | unequal_42 | No    |
      | unequal_43 | No    |
      | unequal_44 | Yes   |
      | unequal_45 | Yes   |
      | unequal_46 | No    |
      | unequal_47 | No    |
      | unequal_48 | No    |
      | unequal_49 | Yes   |
      | not_50     | Yes   |
      | not_51     | Yes   |
      | if_52      | no    |
      | if_53      | 0     |
      | if_54      | none  |
      | ifs_55     | small |
      | ifs_56     | none  |
      | ifs_57     |       |
      | and_58     | No    |
      | or_59      | No    |
      | not_60     | No    |

  Scenario: Logic cases 3
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I add these formula properties
      | name       | expression                                                         |
      | empty_61   | empty(prop("Zero"))                                                |
      | empty_62   | empty(prop("When"))                                                |
      | empty_63   | empty(prop("Tag"))                                                 |
      | empty_64   | empty("")                                                          |
      | empty_65   | empty(false)                                                       |
      | empty_66   | empty()                                                            |
      | equal_67   | equal(prop("Num"), 8)                                              |
      | equal_68   | equal(prop("Name"), "notion")                                      |
      | equal_69   | equal(prop("Flag"), true)                                          |
      | equal_70   | equal(prop("Tags"), ["a", "b", "c"])                               |
      | equal_71   | equal(prop("Num"), prop("Zero"))                                   |
      | unequal_72 | unequal(prop("Num"), 8)                                            |
      | unequal_73 | unequal(prop("Note"), "")                                          |
      | let_74     | let(x, prop("Num") * 2, x + 1)                                     |
      | let_75     | let(name, upper(prop("Name")), name + "!")                         |
      | lets_76    | lets(a, prop("Num"), b, prop("Neg"), a * b)                        |
      | lets_77    | lets(a, 1, b, a + 1, c, b + 1, c)                                  |
      | let_78     | let(x, 2, let(x, 3, x))                                            |
      | prop_79    | prop("Flag") ? "on" : "off"                                        |
      | prop_80    | prop("Num") > 5 ? (prop("Num") > 7 ? "large" : "medium") : "small" |
      | empty_81   | empty(prop("Num")) ? "n/a" : format(prop("Num"))                   |
    Then the formula properties show these values for row 1
      | name       | value         |
      | empty_61   | Yes           |
      | empty_62   | No            |
      | empty_63   | No            |
      | empty_64   | Yes           |
      | empty_65   | Yes           |
      | empty_66   |               |
      | equal_67   | Yes           |
      | equal_68   | No            |
      | equal_69   | Yes           |
      | equal_70   | Yes           |
      | equal_71   | No            |
      | unequal_72 | No            |
      | unequal_73 | Yes           |
      | let_74     | 17            |
      | let_75     | ADA LOVELACE! |
      | lets_76    | -20           |
      | lets_77    | 3             |
      | let_78     | 3             |
      | prop_79    | on            |
      | prop_80    | large         |
      | empty_81   | 8             |
    Then the formula properties show these values for row 2
      | name       | value   |
      | empty_61   | No      |
      | empty_62   | No      |
      | empty_63   | No      |
      | empty_64   | Yes     |
      | empty_65   | Yes     |
      | empty_66   |         |
      | equal_67   | No      |
      | equal_68   | Yes     |
      | equal_69   | No      |
      | equal_70   | No      |
      | equal_71   | No      |
      | unequal_72 | Yes     |
      | unequal_73 | Yes     |
      | let_74     | 8.5     |
      | let_75     | NOTION! |
      | lets_76    | 5.625   |
      | lets_77    | 3       |
      | let_78     | 3       |
      | prop_79    | off     |
      | prop_80    | small   |
      | empty_81   | 3.75    |
    Then the formula properties show these values for row 3
      | name       | value |
      | empty_61   | Yes   |
      | empty_62   | Yes   |
      | empty_63   | Yes   |
      | empty_64   | Yes   |
      | empty_65   | Yes   |
      | empty_66   |       |
      | equal_67   | No    |
      | equal_68   | No    |
      | equal_69   | No    |
      | equal_70   | No    |
      | equal_71   | Yes   |
      | unequal_72 | Yes   |
      | unequal_73 | No    |
      | let_74     | 1     |
      | let_75     | ROW3! |
      | lets_76    | 0     |
      | lets_77    | 3     |
      | let_78     | 3     |
      | prop_79    | off   |
      | prop_80    | small |
      | empty_81   | n/a   |

  Scenario: Logic type errors
    Given a Grid for formula testing with these properties
      | property | type        | row 1         | row 2      | row 3   |
      | Name     | Text        | Ada Lovelace  | notion     | Row3    |
      | Note     | Text        | Hello, World! | x          | <empty> |
      | Num      | Number      | 8             | 3.75       | <empty> |
      | Neg      | Number      | -2.5          | 1.5        | <empty> |
      | Zero     | Number      | 0             | 7          | <empty> |
      | Flag     | Checkbox    | Yes           | No         | No      |
      | When     | Date        | 2024-03-05    | 2024-12-31 | <empty> |
      | Tag      | Select      | alpha         | beta       | <empty> |
      | Tags     | MultiSelect | a, b, c       | b          | <empty> |
    When I start a new formula property
    Then these formulas show these errors
      | expression                               | error                                                                |
      | join("abc", ", ")                        | join() expects list<any> for "list", got text [1,6]                  |
      | min("abc")                               | min() expects number or list<number> for "values", got text [1,5]    |
      | max("abc")                               | max() expects number or list<number> for "values", got text [1,5]    |
      | sum("abc")                               | sum() expects number or list<number> for "values", got text [1,5]    |
      | mean("abc")                              | mean() expects number or list<number> for "values", got text [1,6]   |
      | median("abc")                            | median() expects number or list<number> for "values", got text [1,8] |
      | timestamp("abc")                         | timestamp() expects date for "date", got text [1,11]                 |
      | minute("abc")                            | minute() expects date for "date", got text [1,8]                     |
      | hour("abc")                              | hour() expects date for "date", got text [1,6]                       |
      | day("abc")                               | day() expects date for "date", got text [1,5]                        |
      | date("abc")                              | date() expects date for "date", got text [1,6]                       |
      | week("abc")                              | week() expects date for "date", got text [1,6]                       |
      | month("abc")                             | month() expects date for "date", got text [1,7]                      |
      | year("abc")                              | year() expects date for "date", got text [1,6]                       |
      | dateAdd("abc", prop("Num"), "days")      | dateAdd() expects date for "date", got text [1,9]                    |
      | dateSubtract("abc", prop("Num"), "days") | dateSubtract() expects date for "date", got text [1,14]              |
      | dateBetween("abc", prop("When"), "days") | dateBetween() expects date for "date1", got text [1,13]              |
      | dateRange("abc", prop("When"))           | dateRange() expects date for "start", got text [1,11]                |
      | dateStart("abc")                         | dateStart() expects date for "dateRange", got text [1,11]            |
      | dateEnd("abc")                           | dateEnd() expects date for "dateRange", got text [1,9]               |
      | formatDate("abc", "YYYY-MM-DD")          | formatDate() expects date for "date", got text [1,12]                |
      | at("abc", 0)                             | at() expects list<any> for "list", got text [1,4]                    |
      | first("abc")                             | first() expects list<any> for "list", got text [1,7]                 |
      | last("abc")                              | last() expects list<any> for "list", got text [1,6]                  |
      | slice("abc", 1)                          | slice() expects list<any> for "list", got text [1,7]                 |
      | sort("abc")                              | sort() expects list<any> for "list", got text [1,6]                  |
      | reverse("abc")                           | reverse() expects list<any> for "list", got text [1,9]               |
      | unique("abc")                            | unique() expects list<any> for "list", got text [1,8]                |
      | includes("abc", prop("Num"))             | includes() expects list<any> for "list", got text [1,10]             |
      | flat("abc")                              | flat() expects list<any> for "list", got text [1,6]                  |
      | if(prop("Flag"), 1, "one")               | if() branches must have the same type: number vs text [1,21]         |
      | if(prop("Zero"), "truthy", "falsy")      | The if() condition must be a boolean, got number [1,4]               |
      | if(prop("Note"), "truthy", "falsy")      | The if() condition must be a boolean, got text [1,4]                 |
      | if(prop("Tags"), "truthy", "falsy")      | The if() condition must be a boolean, got list<text> [1,4]           |
      | if(prop("When"), "has date", "no date")  | The if() condition must be a boolean, got date [1,4]                 |
      | and(true, prop("Zero"))                  | Every and() argument must be a boolean, got number [1,11]            |
      | or(false, prop("Note"))                  | Every or() argument must be a boolean, got text [1,11]               |
