import { useMemo } from 'react';

import { useDatabaseContext } from '@/application/database-yjs';

import { DashboardHostServices } from '../DashboardUiContext';

/**
 * The host database's services for `DashboardHostContext`: one object that
 * keeps its identity while every service does, so widgets never re-render for
 * host row-map or loading-state changes.
 */
export function useDashboardHostServices(): DashboardHostServices {
  const {
    addPage,
    bindViewSync,
    canComment,
    canShare,
    canWrite,
    checkIfRowDocumentExists,
    createDatabaseView,
    createRow,
    createRowDocument,
    databaseDoc,
    deletePage,
    duplicatePage,
    duplicateRowDocument,
    eventEmitter,
    generateAISummaryForRow,
    generateAITranslateForRow,
    getViewIdFromDatabaseId,
    loadDatabaseRelations,
    loadRowDocument,
    loadView,
    loadViewMeta,
    loadViews,
    navigateToView,
    openPageModal,
    readOnly,
    scheduleDeferredCleanup,
    searchMentions,
    updatePage,
    uploadFile,
    variant,
    workspaceId,
  } = useDatabaseContext();

  return useMemo(
    () => ({
      addPage,
      bindViewSync,
      canComment,
      canShare,
      canWrite,
      checkIfRowDocumentExists,
      createDatabaseView,
      createRow,
      createRowDocument,
      databaseDoc,
      deletePage,
      duplicatePage,
      duplicateRowDocument,
      eventEmitter,
      generateAISummaryForRow,
      generateAITranslateForRow,
      getViewIdFromDatabaseId,
      loadDatabaseRelations,
      loadRowDocument,
      loadView,
      loadViewMeta,
      loadViews,
      navigateToView,
      openPageModal,
      readOnly,
      scheduleDeferredCleanup,
      searchMentions,
      updatePage,
      uploadFile,
      variant,
      workspaceId,
    }),
    [
      addPage,
      bindViewSync,
      canComment,
      canShare,
      canWrite,
      checkIfRowDocumentExists,
      createDatabaseView,
      createRow,
      createRowDocument,
      databaseDoc,
      deletePage,
      duplicatePage,
      duplicateRowDocument,
      eventEmitter,
      generateAISummaryForRow,
      generateAITranslateForRow,
      getViewIdFromDatabaseId,
      loadDatabaseRelations,
      loadRowDocument,
      loadView,
      loadViewMeta,
      loadViews,
      navigateToView,
      openPageModal,
      readOnly,
      scheduleDeferredCleanup,
      searchMentions,
      updatePage,
      uploadFile,
      variant,
      workspaceId,
    ]
  );
}
