export {
  getInvitation,
  acceptInvitation,
  getRequestAccessInfo,
  approveRequestAccess,
  sendRequestAccess,
  getShareDetail,
  sharePageTo,
  sharePageToGroup,
  sharePageToGroups,
  revokeAccess,
  revokeGroupAccess,
  turnIntoMember,
  getShareWithMe,
} from '../js-services/http/access-api';
