export {
  addAppPage as add,
  updatePage as update,
  updatePageIcon as updateIcon,
  updatePageName as updateName,
  favoritePageView as favorite,
  duplicatePage as duplicate,
  moveToTrash,
  restorePage as restore,
  movePageTo as moveTo,
  copyPageToWorkspace as copyToWorkspace,
  getCrossWorkspaceCopyTask,
  CrossWorkspaceCopyTerminalError,
  waitForCrossWorkspaceCopyTask as waitForCrossWorkspaceCopy,
  deleteTrash,
  createSpace,
  createSpaceWithInitialPage,
  updateSpace,
  createDatabaseView,
} from '../js-services/http/page-api';
